### ISSUE TITLE
[BUG] Counter on trees isnt updated in some cases

### ISSUE THREAD

**Issue by AzaroQL** [sunflower-land/sunflower-land#1251]
## Summary of Bug

If left less than 59secs(?) till tree is ready to harvest, counter freezes and updates only on hover.

## Steps to Reproduce

1. Chop a tree, wait till last minute before it is ready.

## Expected Behavior

Counter is updated each second.

## Actual Behavior

Counter freezes.

## Screenshots

https://user-images.githubusercontent.com/9656961/179926143-7c2deef8-2a61-440f-910d-80fa60b97fb0.mp4

- Device: PC
- OS: Windows 11
- Browser/App: Edge
- Version: 103.0.1264.49

**Comment by Demonbane18** [comment]
looks like a bit of same bug on the chickens back then, probably lord spencer would be able to fix it the same way?

**Comment by nozeroctnellav7** [comment]
Looks like the same bug on crops as well? It's kinda strange my countdown timer ends faster than the crops, despite I set the timer after I planted all seeds (few seconds delay logically). I've triple checked the time required and pretty sure doing nothing wrong. Been noticing this since approximately a month ago. Would like to know if this issue is just on my end. Thanks!

**Comment by Alcharyx** [comment]
The counter update every "save", if you spam "save" you will get it updated. It's not a live counter
