### ISSUE TITLE
[DISC] Floating Point Precision

### ISSUE THREAD

**Issue by j923sneaks** [sunflower-land/sunflower-land#159]
Hi all! I would like to open an issue to discuss floating point precision in relation to the game. We can close this if no action will be done,

The motivation for bringing this up is because I was playing with the code and buying seeds. Then at one point, it says I don't have enough balance even though the display shows sufficient amount. What I did was log `state.balance`

```
console.log('old state balance', state.balance - totalExpenses);
```

![image](https://user-images.githubusercontent.com/89294757/150681283-3cf95f00-d26e-42ee-8dea-ca193d57daab.png)

Since prices decrease after each halving, we will have seeds less than 1 SFL. We can imagine this happening when crafting items as well.

Example:
1. Item requiring 20 SFL
2. Balance is at 19.9996 SFL but display says 20 SFL

Here are my thoughts:
- is it critical to implement? Given that it only affects decimals
- what's the best solution? I am aware of using open source libraries but it might introduce a big change

What do you guys think? 🤔

**Comment by adamhannigan** [comment]
@j923sneaks Thanks for bringing this up.

We faced a similar issue in the last repo and ended up using the `decimal.js-light` package to help out. Given the virality we had last time, we should be prepared for this game to scale quickly and the halvenings to come quite quickly - hence we should be prepared and supporting the decimal points.

We have 2 sources where we will be loading data:
- Web3 (Directly from the smart contracts)
- Our API

Both of these will have decimal numbers.

When we deal with numbers we will need to be consistent. It would be good to introduce the conversions on the business logic layer (e.g. GameProvider and events) instead of trying to do conversions in the UI - This can get a bit messy when/if someone forgets to add it in one place.

There are a few packages that can help us out - `decimal.js-light` was a very lightweight package that satisifed our needs last time. 

It would be good for us to get this in sooner rather than later 💪

**Comment by j923sneaks** [comment]
@adamhannigan thanks for the response. I didn't know we had this on the last repo. Sadly I don't have a local copy for reference. 

I'll try to look into it. I can't promise it will be done this week but if anyone wants to submit a PR, feel free to do so! 🚀

**Comment by adamhannigan** [comment]
@j923sneaks I actually came across a few floating point issues in the Withdraw feature - https://github.com/sunflower-land/sunflower-land/pull/176

I have added in Decimal JS to help us out. Essentially, we just use a `Decimal` type instead of `number` and use the in built methods.
