### ISSUE TITLE
Frog

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#163]
Steve Woody: I’d love to get some ideas about a frog that sits on a lily pad on the pond, also a mushroom stool that goes next to the pond with the frog on it (a mushroom frog)

This Frog will be used as an NFT that all players instantly get with their farm.

Over time you will be able to feed it and mutate it into different types.

**Comment by paluras** [comment]
![fROG](https://user-images.githubusercontent.com/98059798/150685307-86429415-4f43-4873-bc4a-d8391ffec4e2.gif)

**Comment by soteleon** [comment]
![frog](https://user-images.githubusercontent.com/94320699/150685385-b5adf5f7-65ca-4894-b2b5-42a2c1980321.png)

**Comment by AyoubRhalam** [comment]
![image](https://user-images.githubusercontent.com/43474459/150685415-a4694fb8-e98f-4e29-83bc-f42e8b298e20.png)

**Comment by AyoubRhalam** [comment]
![image](https://user-images.githubusercontent.com/43474459/150685428-3995c020-a82b-4293-ac8f-e4fdac528d92.png)

**Comment by Aestnelis** [comment]
![biggfrogon](https://user-images.githubusercontent.com/98103679/150685393-b05ba0bd-bca6-4607-bf12-722c4447d7f3.gif)
![liifrogonnnn](https://user-images.githubusercontent.com/98103679/150685514-bd4a2da7-2e1f-4399-a96f-c0d0f16e0ebe.gif)



![sunflowerfrog](https://user-images.githubusercontent.com/98103679/150685575-f76fb239-88e3-47ca-907f-4e871b8f0b03.png)

![sunflowerbigfrog](https://user-images.githubusercontent.com/98103679/150685580-d4b2c525-3230-4ea4-8e9c-947f95ae264e.png)
![lilfrogpng](https://user-images.githubusercontent.com/98103679/150685623-056a85e3-0ca4-4e5e-a968-00ef34241a3a.png)
![bigfrogsunflower](https://user-images.githubusercontent.com/98103679/150685646-b2fc1ca2-0719-4695-99d4-3bf7a257d290.png)


I can edit, animate or change the colors!

**Comment by ozguradmin** [comment]
![pixil-frame-0 (17)](https://user-images.githubusercontent.com/98276091/150688690-45dc85ba-c487-4200-af33-0cf886a8c418.png)
![pixil-frame-0 (20)](https://user-images.githubusercontent.com/98276091/150688693-c8c6ded4-abd6-4179-8ed3-7a90ae279562.png)
![ezgif-7-1f08faa106](https://user-images.githubusercontent.com/98276091/150688696-a7bdd0b2-05af-40e4-8a1a-341fafe7a565.gif)

**Comment by lucasx194-gif** [comment]
![BOBI (3)](https://user-images.githubusercontent.com/98413590/151019091-b540cb24-9e11-4eb2-a088-8b63248854ff.png)

**Comment by adamhannigan** [comment]
@Aestnelis Fits well on the map 🤗 

<img width="354" alt="Screen Shot 2022-02-01 at 11 06 43 am" src="https://user-images.githubusercontent.com/11745561/151983204-849e4ca8-268f-499e-ad82-655fd596d428.png">

**Comment by Sarapico** [comment]
Im trying to make some friends for Lilly, or some mutations XD.
![pixil-frame-0 (4)](https://user-images.githubusercontent.com/98893182/152438909-279fbac0-a473-4ef6-8856-8b025e9e351c.png)![pixil-frame-0 (10)](https://user-images.githubusercontent.com/98893182/152438941-ed2c569a-29ed-4e1b-b66e-8fd82b88f630.png)
![sapito](https://user-images.githubusercontent.com/98893182/152439019-fde03972-feae-4e5b-ac8d-8fa866e9c18b.gif)![pixil-gif-drawing (1)](https://user-images.githubusercontent.com/98893182/152439039-29b1a72c-43f7-4d96-bc3a-e8ce1b8ea50e.gif)

![pixil-frame-0 (8)](https://user-images.githubusercontent.com/98893182/152439068-b4e2cdfe-bbb4-44a0-8faa-4fa0f4b61469.png)

**Comment by yuritsukahara** [comment]
![frog_totem](https://user-images.githubusercontent.com/2537495/152469301-3fbae4b2-3905-4d44-b69a-77204919fc72.png)

**Comment by Aestnelis** [comment]
![Lily with sunflower frogs](https://user-images.githubusercontent.com/98103679/152637077-45090b6f-e8ef-4caf-a6d5-e2c0311c6044.png)
![bigLily with sunflower frogs](https://user-images.githubusercontent.com/98103679/152637126-3731c728-a1de-48c5-88aa-0997226a520e.png)
![bigfrogss](https://user-images.githubusercontent.com/98103679/152637207-1b570f82-b2ee-4cd4-8621-920ec7e2c634.png)

**Comment by Sarapico** [comment]
Im making some new frog versions. i'll try to make some variations too.

![pixil-frame-0 (5)](https://user-images.githubusercontent.com/98893182/152706631-6e61a65c-6a4e-41d2-9e68-a49f4e1a67d9.png)
![pixil-frame-0 (4)](https://user-images.githubusercontent.com/98893182/152706634-c5914933-fb1e-4f92-9011-2fa24b0fbac9.png)
![pixil-frame-0 (3)](https://user-images.githubusercontent.com/98893182/152706668-07cbc1f8-d20b-4ffc-9d33-3402caa8229e.png)

**Comment by Sarapico** [comment]
More frogs. just because im addicted to their cutness.

![pixil-frame-0 (6)](https://user-images.githubusercontent.com/98893182/154975305-d624c846-771b-4b7f-8867-1de7c34c7ae0.png)![pixil-frame-0 (8)](https://user-images.githubusercontent.com/98893182/154975337-2b69d2be-43c0-405e-be33-2497f3ca8b33.png)![pixil-frame-0 (1)](https://user-images.githubusercontent.com/98893182/154975371-4c5dc4e3-71ef-4b39-8173-ea2bef5f46ad.png)![pixil-frame-0 (7)](https://user-images.githubusercontent.com/98893182/154975400-a7126116-81c4-4731-814f-940f528f5c39.png)

![pixil-frame-0 (2)](https://user-images.githubusercontent.com/98893182/154975535-0988c84a-fd35-481d-a002-d682ea702260.png)![pixil-frame-0](https://user-images.githubusercontent.com/98893182/154975562-1128d4d8-f62f-4181-9a3b-55109e1c5930.png)![pixil-frame-0 (4)](https://user-images.githubusercontent.com/98893182/154975592-5cbf6700-4151-471f-a570-053a521584c8.png)![pixil-frame-0 (3)](https://user-images.githubusercontent.com/98893182/154975610-5cda316a-97c3-45dd-b49b-052092a10865.png)

![pixil-frame-0 (5)](https://user-images.githubusercontent.com/98893182/154975701-54879dea-fab2-449f-ad1b-80776b6dd9f4.png)

**Comment by adamhannigan** [comment]
@Sarapico These are great and have an NFT vibe to them? (Unique frogs for each person ;) )
