### ISSUE TITLE
[PROPOSAL] Liquidity Pool - Wishing Well

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#207]
The purpose of this issue is to explore the idea of a gamified wishing well which rewards users who have provided liquidity.

**Problem**

Without liquidity of the Sunflower Land Token, it becomes difficult for players to swap tokens and resources they have earned through the game. Once the game introduces scarce/limited resources (e.g. plutonium), players will need to engage on a secondary market such as QuickSwap to gain these resources.

Having a strong liquidity pool supports these game mechanics and also allows newcomers to join the project by swapping for the Sunflower Land token.

**Rewards Pool**

When players withdraw resources from the game there will be a relative tax which will be used to:

1. Fund the development of the game
2. **Add funds into a rewards pool**

This rewards pool will continuously accumulate whenever players withdraw from the game

## Wishing Well 

Artwork: BigKong (Discord) 🏆 👏 

![Wishing Well](https://user-images.githubusercontent.com/11745561/151672675-f2248954-6ea2-43b1-9901-60e11cb3b0c5.png)

Each day, a Liquidity Provider will be able to retrieve a proportion of rewards from the pool - based on what percentage of the SFL/MATIC pool they own.

**Requirements to receive rewards**

- Added liquidity to the SFL/MATIC pair
- Liquidity is locked for X amount of days

## Locking Liquidity.

Does anyone have suggestions for a prebuilt tool to lock liquidity or any recommended smart contracts that can do it?

**Comment by defido** [comment]
I feel the "Based on what amount they own" might be something you will need to build. Most lockers as a service only allow locking a certain amount for a time period. I don't think I've seen many that allow removing based on total holdings in %, and even then, will they offer the requirements?

I have looked at some services, they charge ridiculous fees. Which is impractical for lock, unlock, lock, unlock on a daily period.

**Comment by AncientHorse** [comment]
@adamhannigan Is the tax whenever SFL is exchanged as well?  If so, this could be a problem for LPs if the daily exchanged volume greatly exceeds total TVL.

I could generate something that could report how many days a wallet has had an LP position, but it would be shell scripting not smart contracts.  One important thing here is to prevent players from exploiting the system by getting a large LP position then removing most of it.  I could track the initial size of the position then make sure it doesn't go down in size.  Ideally, the forced locking of liquidity is a superior solution.

**Comment by adamhannigan** [comment]
@defido @AncientHorse 

Ideally, the Wishing Well would first grab the total supply of the locked liquidity. It would then figure out what proportion the current account owns of that LP.

I imagine we would need a standard fixed locked time range - i.e. 6 months

We can achieve a similar approach by running daily scripts and seeing who held but there is still room for people to take advantage of the system by depositing/withdrawing LP at the right times.

Sunflower Land Token would only be taxed on withdrawals from the game.

**Comment by AncientHorse** [comment]
@adamhannigan 

I might have a solution for this but the method is different than what you are looking for.  The issue with 6-month locking is the code needs to be created or costs money.  Further, some players might be hesitant to lock SFL for 6 months because they aren't sure if they might need it as the game develops.  Instead of having a 6-month lock, what if the reward was awarded monthly with a status page so players could see how much SFL they are missing out on.

Every 24 hours, a snapshot occurs using a **random** time.  It can record every wallet that has equity in SFL/WMATIC and record the percentages.  A status page will be displayed the day after showing the time of snapshot and all wallets for transparency.  Simultaneously, the status page would show how many SFL tokens were accumulated by withdrawals and the portion each wallet will receive.  I'd need the daily Wishing Well balance available by curl or wget.  

An interesting twist on this would be to award LP providers weekly or even monthly.  This is because the Wishing Well balance will increase over the course of each month and players will see how much they are missing out on.  The math would calculate the daily LP percent then factor in time to accurately reflect the amount that player had in LP.  

A disadvantage is this wouldn't be an automatic process and a coredev would have to manually push the tokens (another reason why monthly might be better).  Ideally, all this information would be entered into mysql but I don't think that's necessary if you just want to kickstart liquidity for 6 months. 

An advantage is that I've already written the hard part of the code for the other module so you'd be able to scratch this off the list of things to do prior to beta shy of incorporating all the metric pages into something that looks nice.  I'm an engineer and can make great data but am useless at making it look pretty.  Trust me on that!

I could also run the scripts simultaneously on one of my VMs and give coredevs access in case anything went wrong or more work was required down the road.

Also, since some players might not know what Liquidity Pool providers do, I could do a custom write up and explain the risks/rewards of it.  Maybe even a separate section of Discord could be created for LPs if there are a lot of new people trying it.  I'll be happy to help all the farmers out in there.

**Comment by adamhannigan** [comment]
@AncientHorse I'm hoping we avoid needing to set up scripts and distribute the rewards to people. There are a few challenges with this:

- We need to maintain the CRON jobs - centralised + room for error
- We need to hold the tokens in escrow before distributing them

No doubt you are capable of creating these services, but it adds an extra set of infrastructure and dependencies on the project that we need to maintain.

Hopefully we can come up with a low maintenance/decentralised solution. Otherwise I think this is a great approach 👌

**Comment by AncientHorse** [comment]
@adamhannigan I agree it's not ideal.  However, if this item puts your launch day at risk, let me know and I'll crank it out.

**Comment by AncientHorse** [comment]
@adamhannigan Here's another possibility.  It's a standalone liquidity rewards pool that you can fund over and over.  So, in theory, it could be automated to sweep SFL and extend the ending block (maybe each day at first, then moving to weekly, then monthly...).

https://github.com/ltonetwork/uniswap-farming

**Comment by j923sneaks** [comment]
@adamhannigan playing the devil's advocate here. Suppose there's an unfortunate event where we need to pull out liquidity (from SFF/MATIC Quickswap LP) again to discourage trading, wouldn't the 3 day wait hinder that?

Example Scenario

1. Day 1 -- deposited SFF/MATIC LP tokens
3. Day 2 -- hack/exploit where we need to pull out liquidity -- cannot withdraw SFF/MATIC LP tokens yet

Your thoughts?

**Comment by adamhannigan** [comment]
@j923sneaks Good catch ;)

In that case we would call `setLockedPeriod` with a period of 1 second. That would enable everyone to pull out

**Comment by j923sneaks** [comment]
@adamhannigan i just realized this will also let users collect SFL rewards multiple times before pulling out 🤔

**Comment by adamhannigan** [comment]
@j923sneaks If an issue does arise, we would change the percentage of withdraw fee that goes into the Wishing pool to 0%

Yes you are right though, there would be a short period where the SFL would just dry up by people quickly searching the well
