### ISSUE TITLE
[PROPOSAL] Pigs / Fertilizer / Bacon

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#213]
Pigs are a new animal in Sunflower Land that will be used for earning new resources that will be used in gameplay and crafting new items.

**Supply**

Unlimited

**Pig**

To craft a pig requires:

- 10 SFL per pig
- Level 3 Farm

Unlimited supply

Please refer to this issue for the artwork request - https://github.com/sunflower-land/sunflower-land/issues/196

**Manure / Fertiliser**

Each day 1 pig produces 1 piece of manure that can be used as fertiliser on crops.

Applying fertiliser to a planted crop increases the quality of the crop which increases the sale price by 2x and the speed of growth by 2x.

**Pork**

After you have fed a pig **wheat** consecutively for 1 week, you can **burn** it for a piece of bacon.

Bacon will be used in NFT crafting recipes and to feed workers which are used to expand land and construct buildings.

**Mud**

If a user crafts mud, it means their pigs will produce twice the amount of manure each day.

Requires:
- 50 pieces of manure
- 20 SFL

Supply: 5000

**Comment by Ramtin9** [comment]
It's Awesome and well-thought-out 👌

**Comment by j923sneaks** [comment]
yeah LGTM! 🚀

**Comment by kimberlite07** [comment]
Maybe make the manure as an ingredient for making fertilizer so we don't get a 1:1 ratio for manure:fertilizer. Also maybe make it 1 fertilizer per field as suggested by @j923sneaks 


Also agree with the cost/reward ratio for being too high. Maybe just choose between the two.

**Comment by Ramtin9** [comment]
Since the supply of pigs is unlimited and some players may craft hundreds of them, it is best to have all the pigs in a pigsty that shows the appearance of a few pigs but written the actual number of them on the sign or when clicked.

However, in this case we have to decide whether the mud should include all the pigs, including the pigs that will be bought in the future, or for example each mud would be usable for every 22 pigs. (depending on the number of fields)

As for fertilizer, my suggestion is that pigs randomly produce three types of fertilizer:
- Brown manure to 2× sale price
- Black manure to 2× growth
- Golden manure that has both properties but is rare

And we can even add a feature that when we click on the planted crops, if we have fertilizer, a small window appears horizontally above or vertically to the right-side of the crop so that the players easily select and apply desired fertilizer. (1 per crop)

**Comment by adamhannigan** [comment]
@Ramtin9 Golden Manure - For some reason I love this! 😆

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
