### ISSUE TITLE
[BUG] Incorrect land count for buildings in workbench

### ISSUE THREAD

**Issue by Whisil** [sunflower-land/sunflower-land#2496]
## Summary of Bug

Count of needed land is wrong when trying to build something using workbench

## Expected Behavior

If building with "Buildings" menu, to build a Deli I need 12 land expansions

## Actual Behavior

If building with "Workbench", to build a Deli I need 9 land expansions, hovewer it's just won't work and shows 9/9

## Screenshots

![image](https://user-images.githubusercontent.com/59148128/234695340-0c768428-636d-4ecd-b5db-17cc0be303a4.png)
![image](https://user-images.githubusercontent.com/59148128/234696283-c56b49d3-582b-4165-a649-9b79840a51e5.png)

**Device Information:**

- Device: PC
- OS: Windows
- Browser/App: Chrome
- Version: 112

**Comment by d4nc3r** [comment]
I see this as well, it actually shows everything in the workbench as 6/6 (which is where I am at with land), except for the Water Well which completely skipped the level I'm at (I'm eligible for my second) and is now showing it requires 10.  Seems to be a bug explicitly on the workbench, the basket appears accurate still.
![image](https://github.com/sunflower-land/sunflower-land/assets/11279931/9483a25c-9989-4c2b-a869-a90025d68ed5)

**Comment by joaoantoniomartinsfilho** [comment]
Does this bug still happen? Because I have just checked out and the land needed is the same in Workbench and Buildings.

![**Workbench**](https://github.com/sunflower-land/sunflower-land/assets/16046723/da096aaa-6d79-4f21-9d75-e0fcab69ffb9)

![**Buildings**](https://github.com/sunflower-land/sunflower-land/assets/16046723/4819fd44-6b53-4e62-b668-36d24dc75013)

**Comment by Whisil** [comment]
Yeah it's correct now, I guess the team fixed it)
