### ISSUE TITLE
[PROPOSAL] Liquidity Pool Based Prices

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#285]
The aim of this proposal is to explore a new mechanism for in-game sale prices.

**Opportunity**

Every in-game resource will be trade-able on secondary markets. This adds an extra layer of strategy to the game as players decide which items to plant/harvest.

Each item will have:

- Total Supply
- Circulating Supply (tokens not on farms)
- Exchange Rate (e.g SFL -> Wood rate)

##Proposal

Each day, set the sale price for an item based on the exchange rate in the Liquidity Pool.

For instance, if there is a liquidity pool between Sunflowers and SFL, we can use that to determine what the in-game sale price of the Sunflower Crop is.

As the amount of Sunflowers in circulation increase, the SFL price will likely drop. This means that in the game you would receive less when selling a sunflower. This acts as a natural scarcity mechanic where the resources receive less rewards over time

If someone decides to buy all the Sunflowers on the market when a new NFT requiring sunflowers is released, it would drive the price for Sunflowers up. This would in turn increase the demand and the sale price of Sunflowers in the game. There would be a short mad rush to plant Sunflowers and sell them.

**Liquidity Pool Based Items**

- Wood
- Stone
- Gold
- Iron
- Eggs
- Sunflowers, Potatoes + all other crops

**Comment by zeldamajora** [comment]
that's a good proposal i think but i have a question  about halving is it going to keep applying on these resources or price depends on market?

**Comment by zinkkrysty** [comment]
If the price is set once per day, then wouldn't some of the liquidity providers be able to manipulate the price by adding or withdrawing liquidity?

E.g. if they know the price is set at 9:00am each day, then they could manipulate the price just before the price in-game is set, then buy a bunch of tokens in-game because the price is cheaper for the rest of the day, then sell them the next day at a higher price.

Probably my example doesn't fully make economic sense, as I haven't thought it through, but wouldn't this introduce some kind of exploitable mechanism?

As a minimum protection against this, the time of the day when the price is updated should be random.

**Comment by adamhannigan** [comment]
@zeldamajora The new system would be a mix of the halvening the liquidity pool mechanics.

@zinkkrysty It would perform an average of the last 24 hours (every hour or so). We would add a bit of randomness to when these values are captured as well to prevent these sort of case :)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
