### ISSUE TITLE
[PROPOSAL] Skill/Progression system

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#390]
All games employ a sense of progression to keep players engaged and grinding towards a new goal.

The aim of this proposal is to explore a system that will engage current and future players to continue playing the game. 

**Goal**

Implement a basic MVP progression that keeps players engaged on launch (2-3 weeks) and encourages them to keep grinding. The goal is not to design a complex system that will take a year to build. We want only the minimum viable product so we can gather feedback, test and improve.

### Skill Tree

Players can choose a path of skills when they level up. This supports the idea of 'specialised' farms in Sunflower Land.

One of the most beloved farming inspired games does a good job with this - https://stardewvalleywiki.com/Skills.

**Skills**

_MVP only includes 2 skill on purpose for simplicity_

- Farming
- Gathering

**Progression**

Harvesting a crop would increase your farming experience.

Chopping wood or mining stone would increase your gathering experience.

### Upgrades

Every 5 levels you advance, you will pick a skill path.

**Farm Level 5**

1. Crops are worth 25% more (Green Thumb)
or
2. Animals yield 20% more goods (Animal Whisperer)

**Farm Level 10**
1. Crops grow 50% faster  (Green Thumb)
or
2. Chickens produce eggs 2x.(Animal Whisperer)
or
3. Cows produce milk 2x.(Animal Whisperer)

**Level 5 Gatherer**

1. Increase wood return rate by 30%
or
2. Increase stone return rate by 20%

**Level 10** 

1. Axes last longer (2 trees with 1 axe)
or
3. Gold drops double.

### Level use cases

1. Mint a special badge to show on your farm
2. Gain boosts
5. Access rare NFTs. For example, you would need a level 7 farm to mint the Chicken Coop

**Farm Level**

Your farm will also be denoted an overall level to display your proficiency. We won't reveal too much but this will be used in the games lore and the fight between Goblins and humans

**Comment by Rofrtd** [comment]
I love the idea o specialized farms. 

Level 10 option 2 (Gold drops double) could be +1 gold on every drop so the max drop is 3, to balance a bit with the other option.

**Comment by SFL-Aeon** [comment]
Curious. Would you be able to reset your skill path? Someone may pick one path and decide that wasn’t the right path they wanted. I know it wouldn’t be something you want to repeatedly allow to prevent them from abusing the system. But most games allow a reset. Maybe lock it every month or 6 months. Whichever seems more balanced.

was the idea to only have 2 options to pick from each 5 level? Maybe give some specialization into the crop growth so ie Level 15 you have a choice to select a certain crop/crops that receive a boast instead of it being all crops. So radishes give 35% more SFL and grow 35% faster, parsnips gives 30% more SFL and grow 30% faster, cauliflower gives 25% more SFL and grows 25% faster.

the same can be done about resources.

my concern is with this system, it should be locked to the crops you grow. Similar to the conversation about the golden cauliflower, it shouldn’t be exploitable so you are trading crops from other farms and selling them for increase profits here.

**Comment by SteveChickenCX** [comment]
I Like this idea, It's simple and intuitive.
we can take some inspiration from RuneScape skills too for future development : https://runescape.fandom.com/wiki/Skills

I suggest tuning down the numbers to allow us better scaling for upcoming levels in the future, It's better to start slow than starting fast and ending out with a level 20 skill that 4X your gold drop.

Farm Level 5

Crops are worth 10% more (Green Thumb)
or
Animals yield 15 % more goods (Animal Whisperer)
Farm Level 10

Crops grow 20% faster (Green Thumb)
or
Chickens produce eggs 1.25x.(Animal Whisperer)
or
Cows produce milk 1.25x.(Animal Whisperer)

Level 5 Gatherer

Increase wood return rate by 15%
or
Increase stone return rate by 10%

Level 10

Axes have 20% chance to not disappear when chopping down a tree
or
Wood Pickaxes have a 20% chance to not disappear when mining an ore

 
Ill add a list of attributes I think we can tweak when leveling up a certain skill

Crops:
1. More yield per crop. (1.2X Flat from cali)
2. Crops worth more. (Flat increase in 10% of worth)
3. Crops grow faster. (Flat growth speed 10%)

So these were the flat benefits but they are kinda **boring**, Let's get some random features in here! 
1. % Chance to double the yield (20% to double the yield)
2. % Chance that one crop will finish up 10-100% faster. 
3.  % Chance to not consume a seed when planting a crop.
4. % Chance for a bigger stack of seeds when syncing.
5. % Chance to sell an harvested crop in 1.5X the price.

**People Love To Hate randomized feature** but they are addictive and far more interesting than a flat value, we can see an example of that behavior in our discord pay attention to how many people are bragging about finally getting 2Gold and not 1.
Getting lucky is fun, Getting unlucky is less fun but triggers you to try again, just like lottery and lootboxes in games.


If you loved the idea of random feature lemme know and Ill add more ideas for Mining and Woodcutting.

**Comment by SteveChickenCX** [comment]
> Curious. Would you be able to reset your skill path? Someone may pick one path and decide that wasn’t the right path they wanted. I know it wouldn’t be something you want to repeatedly allow to prevent them from abusing the system. But most games allow a reset. Maybe lock it every month or 6 months. Whichever seems more balanced.
> 
> was the idea to only have 2 options to pick from each 5 level? Maybe give some specialization into the crop growth so ie Level 15 you have a choice to select a certain crop/crops that receive a boast instead of it being all crops. So radishes give 35% more SFL and grow 35% faster, parsnips gives 30% more SFL and grow 30% faster, cauliflower gives 25% more SFL and grows 25% faster.
> 
> the same can be done about resources.
> 
> my concern is with this system, it should be locked to the crops you grow. Similar to the conversation about the golden cauliflower, it shouldn’t be exploitable so you are trading crops from other farms and selling them for increase profits here.

Respec aspect is great and should be implemented, Let it be a rare craftable item then.

Specialization into a certain crop is a good idea too, We can shape it out to be that every 10 Levels you choose a "Big Skill" and every 5 levels you can choose a "Small skill" like 382743827% more sunflower yield, or better a randomized feature!

**Comment by SFL-Aeon** [comment]
I personal don’t think randomization on crop times would be favorable. Most people setup their crops to grow overnight and if they are finishing at different times overnight then that kind of defeats the purpose. I do think randomization in the returns wouldn’t be a bad thing although I must be one of the most unlucky people because my returns are bad lol.

**Comment by SteveChickenCX** [comment]
> I personal don’t think randomization on crop times would be favorable. Most people setup their crops to grow overnight and if they are finishing at different times overnight then that kind of defeats the purpose. I do think randomization in the returns wouldn’t be a bad thing although I must be one of the most unlucky people because my returns are bad lol.

Well let's compare Night cycle vs Day cycle.

Via the Day crop randomization will reward players who visits their farm often, if RNGjesus is on their side they would get a cool surprise, It may even lead them to use different time of crops if all their radishes will be ready in 8 hours they can plant a cali and finish them all around the same time.

Via the night players that got lucky would get the same amount of harvested crops as if they weren't lucky, no dmg here.

It's a tricky feature I agree on that, But Tricky features is fun, surprises are fun, gambling in crypto is fun.

Players who don't like it don't have to choose this skill too :)

**Comment by SFL-Aeon** [comment]
> > I personal don’t think randomization on crop times would be favorable. Most people setup their crops to grow overnight and if they are finishing at different times overnight then that kind of defeats the purpose. I do think randomization in the returns wouldn’t be a bad thing although I must be one of the most unlucky people because my returns are bad lol.
> 
> Well let's compare Night cycle vs Day cycle.
> 
> Via the Day crop randomization will reward players who visits their farm often, if RNGjesus is on their side they would get a cool surprise, It may even lead them to use different time of crops if all their radishes will be ready in 8 hours they can plant a cali and finish them all around the same time.
> 
> Via the night players who got lucky would get the same amount of harvested crops as if they weren't lucky, no dmg here.
> 
> It's a tricky feature I agree on that, But Tricky features are fun, surprises are fun, gambling in crypto is fun.
> 
> Players who don't like it don't have to choose this skill though :)

Oh don’t get me wrong, I agree with what you are saying. If you can limit it during the two then sure I just know people will complain if they planted their cauli at night and they all have different times. That’s why I proposed a static timing. 

The idea is to be a fun game not a 24/7 job. Due to time zones I guess it would be difficult to set these unless you are able to set your time zone via an in game clock. Ie you say I live in eastern time zone so these are my night hours. It’s starting to sound like late game content creation though haha.

I do think it’s a good idea to separate day and night activities. Would like to see the changing of the cycles relative to your own time zone but I understand all of this requires time and work

**Comment by SteveChickenCX** [comment]
> 

I didn't mean to split the game to a real Day and Night cycles I meant that if someone goes to sleep and plant a cali set for 8 hours even if some calis would have their harvest time reduced that won't hurt his "gains" over night.

**Comment by adamhannigan** [comment]
Looks like the Github outage meant my previous responses were not posted 😢 

@SFL-Aeon A reset path makes sense to me 👍 We want to encourage certain specialised farms but players will need a way to reset (i.e. paying resources or doing a quest)

@SteveChickenCX Agreed. If we use smaller values it means we can scale up other levels later in the game.

**Comment by Ramtin9** [comment]
Here's a number of features level ups could bring in:

**Extra fields**

Upgrades:
- Turn the garden below with 5 fields to 10 fields
.OOO
OOOO
.OOO
- Turn the top right garden with 5 fields to 12 fields
...O O
O OO O
O OO O
...O O
- Turn the top left garden with 12 fields to 22
.OOOO
OOOOO
OOOOO
OOOOO
.OOOO

**Crops**

Increase the growth speed of each crop:
- First speed upgrade -> 10%
- Second speed upgrade -> 20%
- Third speed upgrade -> 30% 

Increase the sell profit of crops/Reduce the buy price of crops:
- First upgrade -> 10%
- Second upgrade -> 20%
- Third upgrade -> 30%
(Each Halving can bring up more upgrades)
Or apply upgrades on crops all together:
- Each certain upgrade -> Weat 50%, Radish 40%, Parsnip 35%, Cauliflower 30%...
(There could be limits on how many times different player can upgrade on each halving)

**Tools and recourses**

Reduce the buy price of tools:
e.g. Iron pickaxe (5 woods, 3 irons, 5 SFL)
- Upgrades -> (3 woods, 3 irons, 4 SFL) -> (2 woods, 2 irons, 4 SFL) -> (2 woods, 2 irons, 2 SFL)

Use tools twice:
- Upgrades -> 15% -> 30% -> 50%

Increase the amount of collectable resources on each gathering:
e.g. Gold (1-2)
- Upgrades -> 1-3 -> 2-3 -> 2-4

Reduce the cooldown of resources:
e.g Stone (4 hrs)
- Upgrades -> 3:20 -> 2:40 -> 2

Increase resources:
e.g. Trees (5)
Upgrades -> 6 -> 7 -> 8

**Animals and Goods**

- Decrease the buy prices
- Decrease the required Wheat
- Increase the Goods
- Increase the speed of productions

Also we can add Fruits
Pluck different fruits from different trees and bushes for cooking (an additional function in order to level up, craft or even buy/sell for change)

**Comment by AncientHorse** [comment]
> Curious. Would you be able to reset your skill path? Someone may pick one path and decide that wasn’t the right path they wanted. I know it wouldn’t be something you want to repeatedly allow to prevent them from abusing the system. But most games allow a reset. Maybe lock it every month or 6 months. Whichever seems more balanced.

Maybe pay SFL to reset skill path and burn the SFL?

**Comment by spencerdezartsmith** [comment]
I love this idea and also agree that the @SteveChickenCX on the smaller scaleup numbers.

**Comment by StavC** [comment]
So what do you think about randomization vs flat values
@spencerdezartsmith @adamhannigan @

**Comment by zeldamajora** [comment]
> Here's a number of features level ups could bring in:
> 
> **Extra fields**
> 
> Upgrades:
> 
> * Turn the garden below with 5 fields to 10 fields
>   .OOO
>   OOOO
>   .OOO
> * Turn the top right garden with 5 fields to 12 fields
>   ...O O
>   O OO O
>   O OO O
>   ...O O
> * Turn the top left garden with 12 fields to 22
>   .OOOO
>   OOOOO
>   OOOOO
>   OOOOO
>   .OOOO
> 
> **Crops**
> 
> Increase the growth speed of each crop:
> 
> * Upgrades -> 10% -> 20% -> 30%
> 
> Increase the sell profit of crops/Reduce the buy price of crops:
> 
> * Upgrades -> 10% -> 20% -> 30%
>   (Each Halving can bring up more upgrades)
> 
> Or apply upgrades on crops all together:
> 
> * Each certain upgrade -> Weat 50%, Radish 40%, Parsnip 35%, Cauliflower 30%...
>   (There could be limits on how many times different players can upgrade on each halving)
> 
> Increase the seed amount on stock per sync
> 
> **Tools and recourses**
> 
> Reduce the buy price of tools: e.g. Iron pickaxe (5 woods, 3 irons, 5 SFL)
> 
> * Upgrades -> (3 woods, 3 irons, 4 SFL) -> (2 woods, 2 irons, 4 SFL) -> (2 woods, 2 irons, 2 SFL)
> 
> Use tools twice:
> 
> * Upgrades -> 15% -> 30% -> 50%
> 
> Increase the amount of collectable resources on each gathering: e.g. Gold (1-2)
> 
> * Upgrades -> 1-3 -> 2-3 -> 2-4
> 
> Reduce the cooldown of resources: e.g Stone (4 hrs)
> 
> * Upgrades -> 3:20 -> 2:40 -> 2
> 
> Increase resources: e.g. Trees (5) Upgrades -> 6 -> 7 -> 8
> 
> **Animals and Goods**
> 
> * Decrease the buy prices
> * Decrease the required Wheat
> * Increase the Goods
> * Increase the speed of productions
> 
> Also we can add Fruits Pluck different fruits from different trees and bushes for cooking (an additional function in order to level up, craft or even buy/sell for change)

i like the idea ,and about extra field  i think it's healthy if upgrade go slowly (ex, 1field per upgrade ) and add a cooldown before upgrading again

**Comment by Z1kou** [comment]
Oh boy, This is a party that i will not  be missing, So lets get this straight, everyone loves having a sense of progression and everyone loves to be unique, This is where this system will come in, everyone here been talking about all sorts of different buffs, imma add some more fun to it:

-I believe that the farm's skill / progression system will only start after u unlock all the fields ,the phase before it of unlocking the field is a sort off tutorial for all newcoming farms , making the fully upgraded 22 crops the new level 1 farm, upon unlocking the level 1 farm you will start to develop a skill tree :

- Divide the skill tree to passives and actives,

- A passive: a skill acquired by hard work, AKA doing the same action over and over

**For Farming** :
 
Level 1 " Basics should be mastered ": ( Farm 88 Sunflower (Easier)/ plant your first 400 seeds of sunflower(Harder) ).

Level 2 " Dirtying your hands " :(  Farm 44 Sunflower & 22 Potatoes (Easier) / Plant your first 200 seeds of potatoes).

Level 3 " From Soil To Soil " :( Farm 66 Sunflower & 44 Potatoes ,22 pumpkins (Easier) / Plant your first 100 seeds of pumpkin),

........

At level 1 you have a passive that gives you 2% bonus on your sunflower yields(Aka every 100 sunflowers collected you have 2 bonus added ), 
At level 2  you get the 2% bonus on your potato yields too

ect...,the more you level up the more efficient you become at farming , 

At level 5 you will have your first active unlocked Farmer's Luck: ( when activated "Cooldown 24hours" you get 5% bonus on your next 100 crops of any types of crops, meaning if you harvest 20 sunflower and after 100 cabbage, you will have 5 cabbage addded to the 100 )

At level 9 you will have the 2% bonus on all of the cultivatable crops (From sunflower to Radishes)

At level 10 you will two paths to unlock( Farmers Luck II: when activated you get 10%bonus on your next 100 crops of any types of crops(wheat excluded), Or Welcoming Farm I: when activated you get 10% bonus on your next 100 crops of wheat )

Meaning at level 10 you unlock the path to either be a better farmer or a better tamer!

**For Chopping / Mining skills** : 

I believe that the huge importance for tools and ressources is that when the  multiple halvenings happen, the price of a tool stays the same this is a core gameplay in the ressources integrity and there importance in the long run , i want us to play around The skills while keeping this in mind:

Now the same kind of buffs would be applied to the  ressources but since they are a bit harder to gather instead of 2% passive increase for every 100 ressource gotten( Aka if u gather 100 wood u get 2 for free, if u gather 99 wood and 100 stones u get only 2 free stones until u complete 100 wood then get 2 woods free too)

We will have it at 1% level 1 ,  level 2 it will be 2% ..... at level 5 since its the first activation you will be given a skill that u can activate every 24 hours (It will be according to what branch you choose either miner or lumber jack, and would give u a 10% increase on top of the passive 5% increase if u gather 100 of a material on that day, meaning if u get 100 wood u get 10 from active then 5 from passive skill on top, same with stone, iron or gold !)


Level 10 you will be a Big boy ressource gatherer with ur Second skill activate ,Ps( Using 1 active skills puts all active skills on the 24 hour cooldown to prevent a farm  being a specialist in everything !), rather than giving u a % bonus the Level 10 skill will give u something precious, A 100 % guarantee chance to get max  value from your next 5 harvests! (meaning if u farm a tree u get 5 woods, same with other ressources)
Again a level 1 farm is needed AKA(22 crops unlocked),

Level 1 "Human Nature": (Chop 1 tree's / 1 Stones)

Level 2 "Wood ? Stone?": (Chop 5 Tree's / 3 Stones)

Level 3 "The Irony": (Chop 10 Tree's / 6 Stones / 1 Iron)

Level 4 "The Irony II" : (Chop 15 Tree's / 9 Stones / 2 Iron)

Level 5 "Collector of all elements" ( Chop 20 Tree's / 12 Stones / 2 Iron / 1Gold )

Now the tree is gonna have 2 branches (AKA 2 paths for players, Miners or Lumberjakes) :
Level 6 "Lumberjack or Miner?" ( Chop 50 Tree's [Lumberjakes PATH] Or Mine 30 Ores[Miner's Path]),

Level 7 "Wood pecker" or "Smelter" ( Chop 25 Tree's Or Mine  10 Ores)
......
AT level 10 we would have a second branching for miners into either a stone,iron or Gold expert, wood is gonna get a good buff too to balance it out, after this the system of rewards would be linear giving every 5 and 10 levels an active Skill while having passives upgrade every 5 levels after the level 10,


 **For Animal Raisors**

You will need to Have a level 1 farm unlocked (AKA 22 crops) & Have the radish meal

Since every animal is unique giving skills to this will be very rough,

I suggest giving a flat boost to everything by applying early on passives on wheat growth first  

Level 1 "Quiet? not anymore" : (Buy ur first Livestock)

Level 2 "You are a Parent now": (Feed your live stock 1 Time),

Level 2 "You are a Parent now": (Feed your live stock 2 Times, // Can be stacked up to 2 times meaning if he had 5 chickens and fed 5 of them only 2 will count to the level up so you don't abuse the system//)

Level 3 "Daily Routine" :(Feed your livestock 3 Times, Can be stacked up to 3 time)
....

At level 5 you get to choose what is your livestock of speciality :
Level 5 "Its getting crowded here" : (Buy 20 chickens Or  Buy 2 cows Or Buy 5 pigs Or Buy 5 sheeps)

Level 6 "Barn? Barney?" :( Sell 200 eggs Or Sell 2 milk Or Sell 5 manures  Or Sell 5 wool)

Level 7 "One with the Barn" :( Sell 400 eggs Or Sell 4 milk Or Sell 10 manures  Or Sell 10 wool)
...
Level 10 "Livestock beyond family" :( Buy 10 chickens and Sell 1000eggs Or Buy 2 cows and Sell 10 milk Or Sell 100 manure and buy 2 sheeps )
....
Other than this the system would be linear of just upgrading the passives / actives every 5 to 10 levels you know the usual

The skill tree for a livestock owner is easier to manage since the player would know what to focus on first it will benifit those who don't buy abit of everything and even reward them more for taking care of all the cute animals!

So now for tha passives and active: 

Passive -Life's Touch  :  Gain 5% Of ressources from animal every 100 collected , this will keep upgrading with A 1% value added to it every level up

Active    -(Level 5) Loving Hands I : Gain 10% Of ressources from animal every 100 collected,Stackable with passive !
             -(Level 10) Fine Breeder I: Have a 10% chance of getting an extra livestock when buying one



Okay I think I covered Most aspects/Possible specialities that will be in the game ,(Forgive me bee lovers) I will stop here for tonight I hope this detailed system that i just came up with would peak your interests, Let me know what you think ❤️ !


Fun Fact:19 March, AKA today is my birthday ! So i thought whats the best way to begin your birthday other than be productive!

**Comment by adamhannigan** [comment]
@Z1kou Nice job 👏 This is my preferred system, but implementing specific quests for each level would be quite difficult to implement and then maintain (make sure we don't break anything when we release new features).

I think we use these, but not as the core gameplay needed to level up.

For instance, you could complete a quest to receive 100 experience points. This would be more progressive than just farming sunflowers randomly

**Comment by Ramtin9** [comment]
One more suggestion is that each 5 level, upgrades farm house design or any other item's designs and small details
It could be freshing

**Comment by Z1kou** [comment]
@adamhannigan , I used specific quests to level up so we won't have any abuse of the system, because it will be easier to monitor what quests break the game if it happens and will give great room in improving the level up system in the long run, I also thought it was the easier way in the short term since we won't have to come up with a Experience per crop system that require heavy monitoring of everycrop with approriate scaling of xp between all of them, Humbled to hear that my staying up till 4 am making a skill system is of help, sleeping happy tonight !

**Comment by adamhannigan** [comment]
@Z1kou I agree with the idea, it would help a lot with engagement.

At the moment it is mostly a technical barrier. We would need to build each custom quest and maintain it. This would require significant work.

**Comment by Z1kou** [comment]
@adamhannigan  Since i just went into calculation of the rewards system in the event I know a little  of the headaches caused by balancing different type of components, My suggestion would be to calculate the SFL Earning of a crop daily and picking the middle crop as the reference of xp giving( Example: A carrot "the refference" would be giving 100 xp , Radish would be then 24000xp and a sunflower would be 1.7 xp (100/60) (so basically to level up a farm you will need at level one 100xp, and keep upping the value depending on the rate of leveling up intended for people to acquire skills,basically saying we want the average of skill acquiring to be 5 days of casual farming, Or 2 days of hardcore farming and adjust the values to the intended function) Idk if im making much sense im just super excited for this , I hope this is easier to test out and gives the intended function for leveling !

**Comment by block-kid** [comment]
I love what I'm seeing here!

A few comments. 

My guess would be, people would prefer % yield increases over crop maturation speed. Closer to the real world, and certain crops are attractive due to their various maturation times.

% increase in sale price is a big win in my eyes.

Suggestions all relatively simple to implement:

**Cooking skill -** combine crops to value add for sale, higher skill higher sale price.
**Self-sufficient skill** - % chance of dropping seeds on harvesting crops
**Crafting skill** - more efficient use of materials, this could be less materials required or greater yields eg the "craft 10" button changes to "craft 12" for the same material cost.
**Husbandry skill** - burn extra wheat or other resources for a % chance of another of an existing animal, require 2+ of that animal.
