### ISSUE TITLE
[PROPOSAL] Anti-botting mechanisms

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#481]
Posting these notes from a discussion by Denlon on Discord. 👏 

1) Try to check window screen size like 1 ip but 2 different accounts are open at 50% of the screen or 4 on 25% screen.
2) Check mouse moving PyAutoGUI python bot module for bots move mouse linear to coordinates its easy check.
3) Check click timeout because 50% bots click < 0.05 sec before another action.
4) MetaMask requests can request a list of all addresses web3.eth.getAccounts() and check if another address register illegally.
5) Check illegal .js script injections, because from Fiddler or Tampermonkey its easy to inject auto actions code.
6) Block IPv6 address because 80% in nft games its low priced proxy multiaccounts.
7) Add checking whats wallets people connect, because good programmers create fake emulated crypto wallet browser extensions and send requests to blockhain.
8) Check syncing actions time on blockhain like harvest 1 hours but people use speedhack and fast send request.
9) And if you add chest positons moving, make coloured chest and add mini noice to image, because Neural Network easy detect imaged items with no color differents and noice.
👀 I work as a tester in other nft games and often notice such vulnerabilities. I write this because i want to invest big sum in SFL and playing. But with this vulnerabilities, bots kill price.
😅 And if need, I can work for you as a vulnerabilities tester or ambassador on russian chat. Sorry for bad english, i use google translate.

**Comment by DonatasDee** [comment]
Lovely!

You know you're doing well when you have bot pro's, people that work on prevention going out of their way to help the project.

**Comment by Denlon210** [comment]
😅 Some more founded by me.
10. Add check anti bot script loading, because if its loading from another website or from single file its easy to block from router, adblock, dns provider, or redirect on hosts windows file.
11. Please no increase land count more 100k because bots easy to mint land and kill game economy on 2 monts, but with lans deficit its not real to cheating on lands count. And + peoples have interest in fighting for ownership of the land profits.
12. Add to smart contracts Anti Re-Entrancy Hack, like people change data more times for 1 block calling to contract, if need, use google to search how to fix.

**Comment by zinkkrysty** [comment]
Why wouldn't a captcha solution be sufficient? If you require everyone to do 1 captcha every day (or every x hundred actions) you can probably eliminate 80% of botting.

**Comment by adamhannigan** [comment]
@zinkkrysty Apologies, missed this one.

There are some low-cost services people can use to bypass captchas. Hence, it is only effective against basic bots

**Comment by RickFaker** [comment]
my 5 cents. i think it is necessary to change once a week or twice a week, the image of chests to new chests, the size of the chest window, etc. It takes time to customize the bots. You, in turn, will mark accounts that failed on the first try.

**Comment by zinkkrysty** [comment]
There is a verification solution available which compiles a signature from a video (using webcam) + audio feed. They claim that everything is done on the client side and does not send any personal details to 3rd parties. The result is a unique Proof of Existence token that is used for authentication in various web3 projects. This is equivalent to KYC in terms of verifying personhood but without exposing private information to anyone.

@sidewindergdao can perhaps explain a bit more about how it works. They would also probably want to hear more feedback about their solution and concerns project devs might have.

[Link to documentation](https://docs.governordao.org/proof-of-existence-documentation/poe-overview)

**Comment by sidewindergdao** [comment]
Thanks for the callout @zinkkrysty 
To expand GovernorDAO sybil resistance solution.

Proof-of-Existence (PoE) is a first-of-its-kind innovation in Sybil resistance providing answers to several of the main issues pervading the crypto space since its inception. Projects can now build out truly decentralized systems that prevent gaming from multiple wallets and bots. 

For the first time, projects can ensure fair governance voting, airdrops and rewards systems, token launches, NFT launches with no gas wars, DeFi gaming, etc. Governor DAOs PoE solves these issues and more, all while guaranteeing the user’s anonymity.

When authenticating yourself to one wallet using Finnovant's revolutionary Say-Tech Technology, users' information for Governor DAOs biometric signup is 100% anonymous and non-intrusive. Persons' biometric readings are hashed locally in the user device, and only the

encrypted output is shared No human ever sees face or voice readings. Say-Tec authentication provides the highest security levels utilizing technology that cannot be predicted, replicated, reused, or replayed.

Proof-of-Existence can bootstrap a project’s engagement and community by leveraging the existing, growing VIP list of authenticated users.Examples for opportunities to "privilege" and resource authenticated users could include:

Early access to incentive programs such as: Hackathons, Trading Competitions, LGEs, Yield Farming, and Token Launches.
It can enable Fair Airdrops or provide Analytics/Data to be used for a Marketplace or Research, It can be used for Fair NFT Launches or Defi Gaming ...

It could even be used for discounts or promotions from any company wether it be retail, phone, entertainment, clothing, restaurants clubs and any other type of goods or service you could think of... It can also be used in Voting in Governance structures or polls/surveys or by using our Governance as a Service (GaaS) model. One line of code can be added to enable the PoE integration into any Smart Contract. Come Check out more information


[GDAO Proof of Existence supporting Sybil Resistance clip](https://youtu.be/AWGEClWMCTY)
[Enrolment portal](https://onlyoneme.governordao.org/)
[Once enrolled mint a ERC20 Proof of existence token](https://passport.governordao.org/)
[Simple Project integration to check for PoE token](https://docs.governordao.org/governordao-developers/poe-integration-overview)
[Q & A on biometric tec GDAO use](https://finnovant.com/frequently-asked-questions/)

**Comment by LordSamoht** [comment]
> my 5 cents. i think it is necessary to change once a week or twice a week, the image of chests to new chests, the size of the chest window, etc. It takes time to customize the bots. You in turn will mark, accounts that failed this test, on the first try.

@RichFaker how are you doing?

I thought about an alternative proposition: Instead of changing it weekly, selecting an artwork at random and applying one or two overlays, at least one animated, would stop a lot of macros, for example, we could have a wooden chest (base image) with a simplre broken padlock (overlay 1) and vines (overlay 2) under a rainbow effect (animated overlay), and the very nest crop, we'd be treated with a iron chest (base image) with a combination lock (overlay 1) and spider webs (overlay 2) under a rain effect (overlay 3).

This could deter simple and intermediate macros that have image detection and noise nullifiers, it would be too much trouble for a common bot developer to work around.

Also it would be a great oportunity to open art contests for the community at later dates.

**Comment by LordSamoht** [comment]
> @zinkkrysty Apologies, missed this one.
> 
> There are some low-cost services people can use to bypass captchas. Hence, it is only effective against basic bots

Hello @adamhannigan , how are you doing?

Most of these services work around common captcha providers, so if a system is developed for the game, specially if it's a unique captcha system, most of these services wouldn't bother to create a new specific counter unless there was very high demand.

I proposed a variable captcha system at issue #806 , basically, the idea is it would choose at random a captcha system for the user. If we can not only vary which captcha is used, but also develop them with unique twists, we can counter not only most basic bots but many intermediate bots as well, but of course, this would take some time to develop and test properly.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
