### ISSUE TITLE
[PROPOSAL] Delayed Token Launch

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#519]
The purpose of this proposal is to vote on a delayed token launch.

**Why**

The game has been live for 4 days and through community feedback we have discovered a few areas that we would like to improve. Once the tokens go live for trading, all hell can break loose. If we don't have a game and community that is ready to scale we will be destined to fail. On token launch, we need to ensure that we have the systems and infrastructure in place that could be ready to onboard and support up to a million users.

These areas include:

- Improving Discord verification, FAQs and user onboarding
- Improving anti-bot detection 
- Improving the mint verification + blacklisting - We have identified close to 1000 farms that were minted by bots.
- Game Design + [Boost improvements](https://github.com/sunflower-land/sunflower-land/issues/509)

**Proposal**

- Roughly 3-4 weeks to improve the areas listed above.
- Release crafting tier 1 NFTs + cosmetics earlier.

**Comment by DonatasDee** [comment]
Just survive the initial backlash and this is absolutely the right way to go.

Some of the discussions held happened a bit late , hence the delay is very needed.

**Comment by SrCouve** [comment]
It was something I already expected, I agree with this proposal, but I suggest that the possibility of the mint continue on the 15th, since the game is already running, I think it's interesting to release the mint, so that countless players feel that they already have something to do, and also so that players who are actually playing and not just the whales can have the NFTs, considering that with the market released, the whales can buy all the resources without having to plant anything

**Comment by adamhannigan** [comment]
@SrCouve That is an interesting point 👌 Definitely open to something like this.

We do want to reserve some of the items to help drive the demand for tokens (SFL, gold etc.) on the open market when the game launches.

I definitely think we can arrange some to be crafted.

**Comment by DonatasDee** [comment]
@adamhannigan The T1 NFT's should probably be craftable. Alongside fountains and such, the cheaper ones that are in large quantities.

**Comment by DonatasDee** [comment]
Although that being said, you're in risk of bots and spammers minting them in mass..

**Comment by SrCouve** [comment]
> Embora dito isso, você está em risco de robôs e spammers minerando-os em massa.

With the market and Withdrawal closed, the impact of bots in relation to NFTS is reduced for all resources notably, it cannot be played on a single account to do like NFTs, in my view the main advantage of bots is to farm the SFL in several accounts at the same time, when you prevent the exchange of resources you also prevent all the resources of an account from being transferred to one so that he has enough to make an NFT, in my view the mint of NFTs has to be released , but the Withdrawal does not

**Comment by baobaopipi** [comment]
I agree with the delay in the token launch. However, I'm not sure if allowing crafting to be live first would be a good idea. we had created a lot of confusion with the initial plan for the 15th alone, I'm just afraid the community will be more confused if we change it in that way.  

Also on the delay, I think we need some sort of clear examples or infographic before the launch of the token in exactly what is going to happen. 

(some examples of the questions that we get constantly now (and not limited to): 
- Token goes live means the game is officially launched? 
- Crafting and selling on Opensea means we can sell wood on OS right?
- So the game doesn't start until the 15th? Meaning all the progression will be deleted? and so on. 

So my argument is that we should enable/disable all at the same time unless we have clear guidelines on what leads to what and what players can or cannot do in those specific timelines.

**Comment by wildwebd** [comment]
@adamhannigan Believe in your feelings. If you are afraid of not being ready, then you are not.
We must not rush things. "Slow and steady wins the race" 😉 

I agree to delay the token launch, everything you said makes sense.

Giving the possibility to craft NFTs to reward the real farmers and counter the whales : I like the idea.
But not all the NFTs, "to reserve some of the items to help drive the demand for tokens (SFL, gold etc.) on the open market when the game launches" like you said, and to keep the hope of the open beta players to have still some time to craft them.

**Comment by Laoshi-Ferdy** [comment]
We have released the announcement that we can craft NFT on 15 April 2022, both from discord and from the game.

Not to mention we have announced the token launch will be at 15 April 2022.

I believe most of the people not read all the proposal here in github and doesn't really know what is going on behind the scenes, even after you post the announcement in discord that we want to delay the token release to 1 May 2022, based on my experience most of them will not read it all, not to mention it's 4 days left before 15 April 2022. ^^"

In my opinion, we need to consist for everything that we have said before in the previous announcement, and keep release SFL token in 15 April 2022 and some NFT which can be able to craft on that day. ( obviously for the NFT which has no problem to be released on that day)

If the team is not really sure about one feature or NFT to be released at 15 April 2022, only then that specific feature or NFT we can adjust it to be able crafted at 1 May 2022 or maybe more time as much as the team needed.

I think by doing this, people will understand that this game is in "developing mode", not all the feature will be available directly 100% perfect at first, but we as community builder have to kept our promise since day 1 to our player. 

**_If we lose money, we will not lose anything. If we lose trust, we will lose "everything"._**

Nice job for all of us.

**Comment by SrCouve** [comment]
> I agree with the delay in the token launch. However, I'm not sure if allowing crafting to be live first would be a good idea. we had created a lot of confusion with the initial plan for the 15th alone, I'm just afraid the community will be more confused if we change it in that way.
> 
> Also on the delay, I think we need some sort of clear examples or infographic before the launch of the token in exactly what is going to happen.
> 
> (some examples of the questions that we get constantly now (and not limited to):
> 
> * Token goes live means the game is officially launched?
> * Crafting and selling on Opensea means we can sell wood on OS right?
> * So the game doesn't start until the 15th? Meaning all the progression will be deleted? and so on.
> 
> So my argument is that we should enable/disable all at the same time unless we have clear guidelines on what leads to what and what players can or cannot do in those specific timelines.

these questions are simple to answer, and the question of NFTs is simple, just make a warning like this:
![lançamentto](https://user-images.githubusercontent.com/98098233/162704710-f3e768cf-28ac-4286-9e51-28f3023c58fe.png)

**Comment by NiielsP** [comment]
To be honest, I feel like it's a good thing. Because if we don't delay the token and allow players to sell their ressources on the 15th, it will be a mess.
For exemple : there is 4.7k wheat in circulation
Let's say we have 193 people that wants to craft kuebiko on the 15th.
Then more than 110k wheat is needed. But as no one will be even close to have 600 wheat, then they will need to buy it from the market. So we will have a crazy high demand and no one to supply. Then wheat will be worth like 20$ and it doesn't make any sense.
Same goes for wood and the beaver, 1.4M demand or so, and 300k supply right now. Wood would be crazy expensive as well.

So as a beta tester I would love to see the token go live on the 15th, but hjonestly, it will be mayhem regarding ressources and their prices.
(Unless the prices of the NFT are changed, but I do believe the prices will still be high so the supply would not be enough)

**Comment by mrbeastgarden** [comment]
I don't mind the token delay but you need to reduce some of this NFT prices and instead put a larger supply.

**Comment by SrCouve** [comment]
Something that worries me is the accumulation of SFL for another two weeks without being removed, and few burns because the NFts cannot be minted yet, an interesting alternative would be an exclusive collection of decorative NFTS for this period, which could only be minted during the next two weeks, in my opinion, would be a good way to stimulate the burning of resources for the launch of the token, and a way to keep players in the game

**Comment by SrCouve** [comment]
Something that worries me is the accumulation of SFL for another two weeks without being withdrawn, and few burns because the NFts cannot be minted yet, an interesting alternative would be an exclusive collection of decorative NFTS for this period, which could only be minted during the next two weeks, in my opinion, would be a good way to stimulate the burning of resources for the launch of the token, and a way to keep players in the game

**Comment by manolman** [comment]
Imo, if you need time to fix important issues that postpone launch of token and withdrawal of items. But let ppl craft nft's. This will take some SFL, gold etc. from cicrulation and reward hard working farmers. They will not craft all of them for sure. So some will be available for crafting. Additionally there will be new ones in the future.

**Comment by tidalnft** [comment]
I agree with delaying the token launch but I think we need to unlock some of the NFTs to be crafted to help burn some resources and SFL that's currently in circulation.

**Comment by denniss98** [comment]
To be frank, this proposal makes a really valid point, it's better for the team and not just the team, the whole community, to launch the token with confidence and implement the crucial features that will contribute to the robustness and reliability of the system. The last thing we want is a failed token launch. 

No rush. I'm in support of the token delay.

Something to keep in mind, something that came up while discussing this proposal with one of my friends;

2 extra weeks is quite a bit of time, 3 weeks in total for open beta testers and countless weeks for closed beta testers. That opens a longer period of gathering resources and potentially will incentivize a larger sell pressure than anticipated for the launch of the 15th.

Perhaps enabling the mint of cheaper T1 NFTs as suggested earlier would encourage players to allocate their resources to those said NFTs and minimize the risk of dumping. Although who knows what the individual community members will do on token launch.

Personally, I'm all for the delayed token launch, also more time to explore any other outstanding bugs and exploits and get a fix in for them too.

**Comment by AlexddrX** [comment]
If you propose a launch before May 1st, there will be too much supply of tokens. The SFL will drop very hard and will cause a large number of players. If you are not ready to turn off the game and start it on May 1st.

**Comment by zAgenTe** [comment]
> 

I agree with what was said, I think there should be an SFL burn during these weeks, and for that to happen, there would be the creation of exclusive NFTs for that period.

**Comment by zAgenTe** [comment]
> Something that worries me is the accumulation of SFL for another two weeks without being withdrawn, and few burns because the NFts cannot be minted yet, an interesting alternative would be an exclusive collection of decorative NFTS for this period, which could only be minted during the next two weeks, in my opinion, would be a good way to stimulate the burning of resources for the launch of the token, and a way to keep players in the game

I agree with what was said, I think there should be an SFL burn during these weeks, and for that to happen, there would be the creation of exclusive NFTs for that period.

**Comment by Stevew00dy** [comment]
Having read all the comments I feel grateful for so many people contributing their thoughts.

No one likes delays but people like failure even less. Some short term pain to prevent some long term suffering is in my opinion, not even a debate. 

As much as I, and everyone really want to see a token launch on the 15th and we all pride ourselves on launching early ... we need to respect the potential impact this can have both for and against.

Pros on delays
- more time to check code and bugs
- ability to catch bad actors and stop them before they cash out
- final checks on the economy and resource impact on the game

Cons on delay
- people will be upset / backlash
- more tokens in circulation to hit the market at once
- lose our early launch credibility 
- support will be overwhelmed

I'm sure there are more but this is what I feel and also from reading everyone above.

Adam, you are doing incredible work and whilst I know in your heart you want to be decentralised .... people are not fully ready for that step yet. Therefore whilst you take advice from people here, you need to do in your gut, what you know is right.

You wouldn't launch a rocket if there was a red light, no matter how small. It would be madness to launch this if you are not 100%

People will overcome their feelings and we can manage their expectations with solid communication and a clear structure moving forward so that it's clear and not rushed. 

We should act quickly to give people time to adjust and also stop and FUD that might appear.

We are in Beta and people need to understand this. We can focus the attention on the bad actors so the community know the reasons for the delay. This also will help them to look out for this people who cheat.

I suggest 

Create a discord channel for those who want to report bad actors, with a limited edition NFT that they can craft if information leads to a ban. Maybe some grass 😳

I also agree with comments about keeping the main NFTs locked to stop a transfer of SFL from bad actors into other assets which will make it harder to track. 

Give it a week to remove as many cheaters as possible and then launch a series of smaller decorative NFTs in larger quantities to burn some SFL and also lock them 1 per account.

Don't launch the SFL token and don't allow any in game utility to further increase SFL minting at this time. 

Maybe this can all be done around lore, a storm hands over sunflower land and if it gets to the point, crop harvest can be affected to help reduce the mint to ease the launch. 

Whatever you decide .. you have my full support.

**Comment by RogGarcia** [comment]
Hello. I support the proposal and agree with the balance of the game, but I have concerns about the amount of tokens that will be generated until this new date and ready for withdrawal (even with the fees applied for small amounts).
I don't know if the liquidity pool will support 50k people making withdrawals in a few days. Perhaps in a first phase it would be interesting to limit the maximum withdrawal amount that, for example, only covers the gas fees spent on synchronization or to release withdrawals by batches, where in a first phase only the first 1000 farms could make withdrawals, then farms 1001-5000, as I believe older users would be more willing to contribute to the liquidity poll...

**Comment by SFL-Aeon** [comment]
I support the delay although I was counting on the token being live to continue planting and resource gathering. I think with the current on going issues and requests a delay is needed. I think though as some users mentioned if the NFTs get delayed that will be a bigger concern for others. I think delaying the most saught after ones would be alright though.

**Comment by Frozenhate** [comment]
from what i hear its not the first sunflower game you make, have you not learned anything? and you also opened a closed beta and still no insight into problems that games like these bring? and now one of your proposals is "On token launch, we need to ensure that we have the systems and infrastructure in place that could be ready to onboard and support up to a million users." Yeah no...you had your time. Many bigger games existed and they all went through their dump phase, if you want your game to endure just go with the flow, its called economy for a reason.

**Comment by Luc0414** [comment]
please do not start with the date changes, much less making an external discussion to the channel that only 1% participates

**Comment by Tambel1979** [comment]
I agree with what many of the commenters have said, and especially with what @Stevew00dy said. The team knows whether a delay is the best path at this point, not the players. To go with the rocket analogy Steve used, if a red light was on but the astronauts still wanted to lift off because they were psyched to go into space, mission control wouldn't okay the liftoff because of their feelings.

One big point I'd like to make is that this issue needs to get out to the players NOW. The big storm over Sunflower Land theme is a good idea, I think. Add it to the lore. Also the Discord channel to identify bots and cheaters, which is the game's biggest threat as evidenced by what happened to SL before.

I'm not an OG, but I really like the game, not just for making money, but for playing. It's peaceful and relaxing and with the possibility of at least supporting your play with what you make down the road. I'm with @adamhannigan on this.

**Comment by Reda2017** [comment]
Hello everyone ! it's my first time on github. i'm enjoying reading proposals and comments :D. i came here to share my opinion.
i am with the proposal if it's better for the long terme economy and the game in general. there are many ppl waiting to buy SFL and mint NFTs just as there's other ppl who just want to dump the token, abuse minting system etc... unfortunately botters, whales, multiaccounts will have impact on the economy. 

i have a suggestion, idk if it was already mentioned. "Minting require level(nft farm)". i have seen similar thing where minting only if you have adequate skill(removed) but could be well replaced with level of the farm in general. this way only engaged and serious ppl will have acces to "certain" NFTs. 

We could go with categories. *level of the farm combined (gathering + mining).
- low tier Nfts = available for everyone
- Mid tier Nfts = lvl 10 required
- High tier Nfts = lvl 15 required.

**Comment by FearBoBz** [comment]
a solution that I think would be good to avoid the massive eviction, would be to limit the loot to, for example 10 per day, and banish and fix the bugs, and then release it for loot in the original way. this way the token would be released, the community would not be frustrated, and you would have time to run after the hackers

**Comment by baobaopipi** [comment]
Hey is my updated thoughts after reading all the comments. 

**My Concern :**

- I like the idea of partially unlock of NFTs, but I don't like it if it was just decorative or something totally new just to carter for the delay. 

- Part of the reason V2 is fun for most players is the crafting of NFTs with in-game buffs, it gives them target or 'purpose' for grinding the materials instead of just farming $SFL. 

- While I understand the counter measure of increasing supply is 'burn', but the burning mechanism suggested here can also be treated as 'optional' for certain players.  Having no token in circulation simply means that we have no 'economy' to test the market in early stage until further accumulation of supply. 

- With the token delay and only crafting is available, I'm afraid it will further discourage players to craft but only accumulate $SFL, then cash out when the withdrawal of token is finally available.

- It will result in killing the viability of play styles and further discourage those who don't have 'enough' time to but still want to enjoy the game. The singularity of play style on top of the delay will make the progress dreadful and open a race for hard grinding which take away the fun and flexibility(which are the core enjoyment of the game so far) 

**My Proposal**

- I would like to suggest that we go for the gradually unlocking set up, and applicable to both NFTs & Token at the same time. 

**_NFT_**
- We are starting to have a nice Tier system in NFTs crafting which give the feeling of 'progressiveness' and achievement in grinding. Unlocking NFTs in a gradual way will further strengthen that.

For example: T1 to be unlock first(in the nearest possible), T2(a week later or the next update), and finally T3 should only be available on the official launch (because it doesn't make sense that the 'OP end-game' item can be acquired even before that) 
 
**_TOKEN_**
- As for the Token, gradually unlock would mean withdrawal limit + tax. 

**While I understand that the current Tax System is to encourage the crafting. But this tax design always end up in benefiting botters and hurting the players instead. It is not a prevention but just profits reduction of 25-30%, botters don't care about taxes because profits is profits, and they don't need to pay anything else on top of that. And because of the earning potential, they will end up paying lesser tax than generic players.** 

- A solution to this can be done by setting tax deduction on top of the 'gathering' skill level. For example, 30% at level 1, and scaling non-linearly(just like with the current EXP system) to 5%(or 0%) at level 10.  This will encourage : 
1. Crafting and mining at the earliest
2. Fair for players who spending resources to craft and mine
3. And reduce the withdrawal of botters with the initial design. 

- A withdrawal limit can be set up together with the gradually launch of NFTs. I think the team can calculate the potential income of generic players vs botters easily. We can set the limit according to the average earning (or slightly higher) of generic players, thus further limiting botters to dump. 

- An increase of withdrawal limit aligning with launch of Tiered NFTs suggested earlier will also help in balancing the supply & demand for both sides. 

I hope my points can give you guys some different point of views regarding this. As much as we want to show support for the team's vision we also need to take a step back and look at the bigger picture with real world indication. 

**sometimes we get carried away by sentiments because of the emotions investment in the project, especially for those who have been with the team for a longer time. However is important to remember that we are still at the early stage and which rational thinking is very important**

Never the less, we're still the best community. Cheers sunflowers fam!

**Comment by Rouemn** [comment]
If the team believes a delay for the lauch is needed, I support it if a better product and harder measures against bots comes from it. Just post the decision on discord as soon as possible, if done, so the community becomes aware of it.

About the NFTs, being able to craft them (or at least part of them) on the 15th would be a good idea, or the players that already have the NFTs would keep snowballing and have an even higher headstart. Also, having some kind of requirement (like a level requirement) would reward faithful players and give time for the team to deal with some problems.

**Comment by BanInstinct** [comment]
> The purpose of this proposal is to vote on a delayed token launch.
> 
> **Why**
> 
> The game has been live for 4 days and through community feedback we have discovered a few areas that we would like to improve. Once the tokens go live for trading, all hell can break loose. If we don't have a game and community that is ready to scale we will be destined to fail. On token launch, we need to ensure that we have the systems and infrastructure in place that could be ready to onboard and support up to a million users.
> 
> These areas include:
> 
> * Improving Discord verification, FAQs and user onboarding
> * Improving anti-bot detection
> * Improving the mint verification + blacklisting - We have identified close to 1000 farms that were minted by bots.
> * Game Design + [Boost improvements](https://github.com/sunflower-land/sunflower-land/issues/509)
> 
> **Proposal**
> 
> 15th March -> **1st May**. Roughly 2 weeks to improve the areas listed above.

if it's for the good of the game, let it be delayed

**Comment by BanInstinct** [comment]
if it's for the good of the game, let it be delayed. 🌻

**Comment by Ramtin9** [comment]
We support whatever you guys decide that will improve the game ❤

**Comment by adamhannigan** [comment]
Lots of great points we are taking into consideration.

We will be launching the crafting of tier 1 boosts on the 15th and a range of cosmetic items.

@baobaopipi Some good ideas around a gradual withdraw on launch to help stablise the economy 👏

**Comment by Cicciolin0** [comment]
Could maybe consider lowering the 0.1 tax for syncing if the delay actually happens, that would make people happier

**Comment by block-kid** [comment]
I've had the same thoughts around the token as @baobaopipi, another option could be a taxed cooldown period on withdrawals. Examples of possible options:
- daily withdraw limits set at a % of the average farmers daily earnings
- a time diminished tax that resets to maximum after each withdrawal,
    - e.g. the tax starts at 30% and reduces by 1.1% every 24hrs, resulting in a tax of 0% after 4 weeks
- some combination of both

**Comment by Dajoenie** [comment]
I think looking at the industry as a whole there is wiggle room to improve things. Gala Games, for example, has been fundraising and teasing for a long time now and they don't have a blockchain yet.  Last I checked they haven't even named it.  Point being, I don't see a AAA company stepping into this space to steal market position.  That has been one concern of mine.  With that in mind I do think the project  has an opportunity to delay with less dramatics then you would see if problems crop up after launch.

**Comment by Khazix73** [comment]
You have to think about the consequences that a delay could bring, I am mainly talking about scams, many people will create a fake token on the 15th that will destroy the game before the launch and swindle a lot of money that can be beneficial for the game, apart from that the confusion of people not knowing what will happen, if people are deceived they will not trust your game anymore, is just my opinion, I seen NFt projects going down before lunch for the same reason like cryptogodz

**Comment by Yang0510** [comment]
I agree with delaying the token launch but I think we need to unlock some of the NFTs to be crafted to help burn some resources and SFL that's currently in circulation.

**Comment by WUUYE** [comment]
In my opinion, there are pros and cons to a delayed release. But the disadvantages outweigh the advantages. The first is the issue of reputation. The first thing everyone saw when they opened the official website was the token sale on the 15th, but it was postponed. In the midst of a long wait, near release, a sudden delay can make people uncomfortable and feel cheated. Especially those who have been playing v1 and have always believed in the team. Will this cause division among old players, continue to believe or flee? And it will have an impact on attracting new players. Delaying the release will make fewer bots, etc., few people will notice. They will only care that your promise is not fulfilled and lie to them.
Thank you for reading, this is my personal subjective opinion and does not represent the opinions of others.
I used translation, please forgive me

**Comment by blockpanda** [comment]
It's a bad decision, don't get caught in a loop of delays or it will reduce the enthusiasm of the participants
Go live on time, identify issues and resolve them dynamically

**Comment by lets2i** [comment]
Seems like that it already was decided that we will have a delayed token launch.

Here's my issue if it:
- it was already marketed everywhere that the launch is on the 15. , changing the date so close to it, really leaves a bad taste in the mouth for the people and a lot of people are going to lose trust in the project, crypto world is moving fast.
- delaying it by another 2 Weeks will result in 1 halving 100% maybe even 2, making the gap for early people (closed beta) and new players (launch day people) even bigger.
- there shouldn't have been a beta, where you can already farm stuff for the launch in the first place, or at least one, where players don't have a month time to accumulate wealth before the token is launched, but there's no changing that now.

My suggestion would be
- have a launch on the 15. like promised to the players.
- not unlocking every feature right away, like NFTs that are still in discussion.
- launch the token like promised on the 15. and let it have a price discovery stage. There's no economy if it's delayed even further and the token will suffer even more if we have 2 halvings before launch. And letting players accumulate even more SFL in 2 Weeks time is gonna have the token dump harder, which is a really bad look for the investors.
- put a heavy withdraw tax that gradually reduces till the 1.
- gradually unlock more features as they are ready.
- if the team is scared about bots destroying the economy have a heavy tax for newly created farm, so the team can catch up on anti bot measures.
- This SHOULD NOT be marketed as a delayed launch, but instead 'launch' the game, but unlock features as they are ready. The worst thing you could do is saying that the launch is 'delayed' for another 2 weeks.

So all in all, what I can get from the first post is, that the issue lies in bad actors and bots. It's a cat and mouse game, bad actors are going to find a way around it eventually and then it's on the team to get ahead of them.

**Comment by dpx63** [comment]
> It's a bad decision, don't get caught in a loop of delays or it will reduce the enthusiasm of the participants Go live on time, identify issues and resolve them dynamically

I think the same.

**Comment by reymarpabito** [comment]
Wow, so many great ideas and suggestions, amazing! At first, I really like the game to be delayed since there are lots of issues recently regarding people using and selling scripts, bots, auto clicker tools (macro), and doing automation and multi-accounting actions that resulted in lots of farms being blacklisted. I also have collected a few resources for crafting NFTs so the delay can help me cope up haha just kidding xD. 

But then I realized that it's easier to break things than to fix things, meaning - no matter how hard the team patches, fix or solve such issues, these greed-driven individuals will continue to look for vulnerabilities to exploit and automate the game. So I think it's best to handle and combat them dynamically moving forward. Also, Khazix73 has a point that scammers might also be preparing for the token launch this April 15 and might create fake $SFL tokens fooling people to buy them that day. If that happens, most of the scammed people will then spread FUD and bring toxic vibes about the game, ruining Sunflower Land's reputation big-time, similar to what matey Steve said. And I quote:

"It takes 20 years to build a reputation and five minutes to ruin it. If you think about that you'll do things differently."
-Warren Buffett 

Additionally, delaying the token launch as everyone said, can increase the supply of earned tokens per farm account meaning the money-driven individuals - who don't really care about the game - will not be penalized heavily by the tax rates set in place. It will also create a pump-and-dump effect during the delayed token launch date.

Therefore, I agree with some of the people above to continue to launch the token this April 15 since it's already widespread news and announcing a token launch delay might fall short and not reach lots of people. But, same with the suggestions above, certain measures should be put in place. I like GoblinNoLikePotato's idea of a "gradually unlocking set up" both on the token and NFTs which I think is a win-win situation. I like lets2i's insights as well.

LFG Sunflower Land! 😎🚀🌻🔥

**Comment by MarketParticipant** [comment]
The team is in the position to judge whether a delay would solve more issues than it would create.  The rest of us don't have enough information to have valuable opinions.

The fact that you are bringing it up seems to indicate that, based on the feedback from beta, it would have been better to have scheduled a longer open beta period and that it would probably be valuable to extend the beta to fix the largest issues.

In general, the community of players trusts you, and whatever you decide, the vast majority will support the decision.  Based on the reaction to the previous delay it seems pretty obvious that the people who have invested a lot of time or money into the game would rather see it launch well than launch soon.

**Comment by MarketParticipant** [comment]
> The team is in the position to judge whether a delay would solve more issues than it would create. The rest of us don't have enough information to have valuable opinions.
> 
> The fact that you are bringing it up seems to indicate that, based on the feedback from beta, it would have been better to have scheduled a longer open beta period and that it would probably be valuable to extend the beta to fix the largest issues.
> 
> In general, the community of players trusts you, and whatever you decide, the vast majority will support the decision. Based on the reaction to the previous delay it seems pretty obvious that the people who have invested a lot of time or money into the game would rather see it launch well than launch soon.

For people reacting, especially disagreeing, it would be helpful to say which part I am right or wrong about.

**Comment by Aminbtdds** [comment]
I think this is the decision only team members qualified to take, because community loves to see token listing and launch, pure emotions and hype, but team members have enough data and knowledge to speculte lack of improvement in certain measures like anti bot and mint verification would kill our game, So do ur best without rushing things❤🙏

**Comment by Dajoenie** [comment]
I have to change my position on the issue. I think that the idea of imposters trying to sell knock off SFL is very real like some people above me have stated. I believe the damage to people, who don't know any better, are very real.  I believe the damage to the integrity of the project is very real.  Just wanted it on record. I don't want to be morally accountable for my earlier comment should people get hurt.  I think the project should launch as stated and call for all hands on deck to help get through it.

**Comment by appolo99** [comment]
i think if there is no way to handle bugs without delaying token launch, you have to suspend the open beta until launch, halvening is approaching more and more.

**Comment by brian-man** [comment]
> I have to change my position on the issue. I think that the idea of imposters trying to sell knock off SFL is very real like some people above me have stated. I believe the damage to people, who don't know any better, are very real. I believe the damage to the integrity of the project is very real. Just wanted it on record. I don't want to be morally accountable for my earlier comment should people get hurt. I think the project should launch as stated and call for all hands on deck to help get through it.

Agree, though I wouldn't paint it quite so darkly.

Refinement of my position:
- The official SFL token should be launched "on time" (as advertised on Apr 15).
- The LP pool should exist and be usable on QuickSwap.
- It should have at least, I dunno, 1000 SFL of liquidity with some non-infinity exchange rate to Matic.
- Separate decision IMO: should withdraw-sfl-from-farm functionality be delayed or throttled.

**Comment by muco5417** [comment]
I don't want the token sale to be delayed. because everyone will sell and the price will be very low. As a result, we will be disappointed again.

**Comment by Emin43** [comment]
I don't want the token sale to be delayed because I think the value of the token will drop a lot.

**Comment by Emin43** [comment]
I don't want the token sale to be delayed because I think the token's value will be low.

**Comment by bizon35** [comment]
A large-scale vote is required to delay the game

**Comment by vusinwonderland** [comment]
I want to say few things about this game. 
When i first joined and played this game, i thought many good things about it. I recommended my friends and family to play it. Even they didn't know about these type of games, NFT, tokens etc. Even i don't know so much about it. My bf told me to play it. But since then i follow the news about the game and i was very sad when it closed because we just begin to earn and win something, i was discougared but after all the explanations from creators i wait with patience as everyone else. I know that building something from bottom is not that easy. First you guys said it'll take 4-8 weeks. After that you said it'll open on march. After that you opened Beta version on April finally. By the time lots of scam games opened same as SFL, took advantage from your game and scammed people. Still we were waiting patiently. you said token will release on 15 april and everyone get excited about it. I am working 9 to 5 job and i don't have really much time but still i create time for SFL and bring my laptop to work and continue playing. The hype is real and you know that. Everyone got excited.
Now you're saying you'll delay the token on May. I know again building up a game is not that easy i don't know about the technical stuff but I START TO FEEL THE TOKEN AND GAME WILL NEVER RELEASE. You always delay and delay and delay. It's not trustworthy anymore. If you said the game will launch on june or july from the begining it's make more sense then delaying.  I really am discougared. 🥲🥲🥲🥲
I'm thinking about sell my land and don't play it anymore. At least delay it until end of april or don't give us a exact date idk make a surpriese or something 🥲. May is too far. Or at least open it on may this time no more delays. If you read it this far thank you and have a nice day. Good luck

**Comment by raif1637** [comment]
i like new sunflower land  game

**Comment by BanInstinct** [comment]
> I want to say few things about this game. When i first joined and played this game, i thought many good things about it. I recommended my friends and family to play it. Even they didn't know about these type of games, NFT, tokens etc. Even i don't know so much about it. My bf told me to play it. But since then i follow the news about the game and i was very sad when it closed because we just begin to earn and win something, i was discougared but after all the explanations from creators i wait with patience as everyone else. I know that building something from bottom is not that easy. First you guys said it'll take 4-8 weeks. After that you said it'll open on march. After that you opened Beta version on April finally. By the time lots of scam games opened same as SFL, took advantage from your game and scammed people. Still we were waiting patiently. you said token will release on 15 april and everyone get excited about it. I am working 9 to 5 job and i don't have really much time but still i create time for SFL and bring my laptop to work and continue playing. The hype is real and you know that. Everyone got excited. Now you're saying you'll delay the token on May. I know again building up a game is not that easy i don't know about the technical stuff but I START TO FEEL THE TOKEN AND GAME WILL NEVER RELEASE. You always delay and delay and delay. It's not trustworthy anymore. If you said the game will launch on june or july from the begining it's make more sense then delaying. I really am discougared. 🥲🥲🥲🥲 I'm thinking about sell my land and don't play it anymore. At least delay it until end of april or don't give us a exact date idk make a surpriese or something 🥲. May is too far. Or at least open it on may this time no more delays. If you read it this far thank you and have a nice day. Good luck

first, wtf, second where are the devs not meeting deadlines??? they always met with them, 4 to 8 weeks, exactly 8 weeks later, the beta started, and look how the game is, it's beautiful, it's fun, how dare you say that? whoever fell into a scam is dumb, it had nothing to do with the game

**Comment by Dizelek72** [comment]
> Цель этого предложения — проголосовать за отложенный запуск токена.
> 
> **Почему**
> 
> Игра существует уже 4 дня, и благодаря отзывам сообщества мы обнаружили несколько областей, которые хотели бы улучшить. Как только токены будут запущены для торговли, весь ад может разразиться. Если у нас не будет игры и сообщества, готовых к масштабированию, мы обречены на провал. При запуске токена нам необходимо убедиться, что у нас есть системы и инфраструктура, которые могут быть готовы к подключению и поддержке до миллиона пользователей.
> 
> Эти области включают в себя:
> 
> * Улучшение проверки Discord, часто задаваемых вопросов и адаптации пользователей
> * Улучшение обнаружения анти-ботов
> * Улучшение проверки монетного двора + черный список. Мы выявили около 1000 ферм, которые были созданы ботами.
> * Улучшения игрового дизайна + [Boost](https://github.com/sunflower-land/sunflower-land/issues/509)
> 
> **Предложение**
> 
> * Примерно 3-4 недели, чтобы улучшить перечисленные выше области.
> * Выпускайте NFT 1-го уровня + косметику раньше.

I do not support! already go through this. You need to put your word out, since you have given people hope!

**Comment by BanInstinct** [comment]
> > Цель этого предложения — проголосовать за отложенный запуск токена.
> > **Почему**
> > Игра существует уже 4 дня, и благодаря отзывам сообщества мы обнаружили несколько областей, которые хотели бы улучшить. Как только токены будут запущены для торговли, весь ад может разразиться. Если у нас не будет игры и сообщества, готовых к масштабированию, мы обречены на провал. При запуске токена нам необходимо убедиться, что у нас есть системы и инфраструктура, которые могут быть готовы к подключению и поддержке до миллиона пользователей.
> > Эти области включают в себя:
> > 
> > * Улучшение проверки Discord, часто задаваемых вопросов и адаптации пользователей
> > * Улучшение обнаружения анти-ботов
> > * Улучшение проверки монетного двора + черный список. Мы выявили около 1000 ферм, которые были созданы ботами.
> > * Улучшения игрового дизайна + [Boost](https://github.com/sunflower-land/sunflower-land/issues/509)
> > 
> > **Предложение**
> > 
> > * Примерно 3-4 недели, чтобы улучшить перечисленные выше области.
> > * Выпускайте NFT 1-го уровня + косметику раньше.
> 
> I do not support! already go through this. You need to keep your word, since you have encouraged people!

they're keeping their word, i believe if it's for the good of the game, let it be done! can't get the whole project? would you rather the game last 2 weeks and you cash out 10 dollars or create something fun, well done and profitable in the long run?

**Comment by Dizelek72** [comment]
anyway, I'll stay with my owner!

**Comment by Dizelek72** [comment]
zakryt!
it happened last time! And the project is closed!

**Comment by RogGarcia** [comment]
I share the same concern with you @SrCouve . I believe that NFTs should have as a prerequisite, in addition to resources (wood, SFF etc) the level of farming and tools of the farm. For example to make the first scarecrow, your farm should have at least level 5 farming or such XP points. As for the sale of resources, I don't see a problem if these prerequisites are implemented.
