### ISSUE TITLE
Economy Improvement

### ISSUE THREAD

**Issue by KKonst27** [sunflower-land/sunflower-land#526]
**First of all,** I want to express my opinion regarding, as it seems to me, a big hole in the game's economy. Some time ago, I already suggested adding some resource to the NFT recipe that cannot be transferred between farms. Previously, this role was played by grown fruits of plants, which could not be withdrawal on the testnet. Now NFT has lost any minimal fixed equivalent in time.
You want to demotivate users of multi-accounts and bots, but at the same time create favorable conditions for their development. I will explain why: in the crafting of NFTs, the time spent on the production of these resources plays a huge role. And since all resources in NFT recipes can be transferred between farms, this variable can be cleared to zero by simply increasing the number of farms. While one honest player would have to collect resources for this NFT for about a month (as with Kuebiko in my case), the owner of multi-accounts or a botter, having created, for example, 30 upgraded accounts, will collect the same amount of resources in 1 day. I'm already silent if he has even more farms.
In the end, in order to mint the NFT, people will compete not in the right strategy and in the right priorities, but in who can create more farms. Therefore, **I strongly recommend either to prohibit the transfer of plant fruits between farms, or to add some other resource to the NFT recipe that cannot be transferred between farms.** Otherwise, as a result, a pool of abusers will form in the game, which will loot the entire supply of current and future NFTs.

Secondly, I propose to introduce methods for the constant burning of primary natural resources such as wood, stone, and so on. For example, you can implement a slightly more complex crafting system, for wood, enter a sawmill with a carpenter who would process a certain amount of logs into boards that could be used in the creation of NFT, crafting the next level, or sold for SFL to villagers or goblins for various needs. Same thing with stone and other resources. Stone > hewn stone > sell, create NFT, craft the next level.
Also, resources of the 2nd level and above can be used to build and improve buildings. You can also set a timer for processing primary resources. For example, 4 logs + 4 hours = 1 plank. Something along those lines. Perhaps, if I have time, I will throw in a few ways to develop the crafting system.

I see how the developers are trying to create a cool game for us. I appreciate what you do and wish this game will live forever. Thank you for that. Please take a closer look at the first part of what I wrote above.

P.S. I am not a native English speaker. In places, my speech can seem uncouth and rude. Sorry if that's how you feel. In my message, I carry only a positive vibe.

**Comment by ASKONDR** [comment]
I support the author and agree with his every word. We all want this wonderful project to live as long as possible, please with updates and bring a stable income, like a real farm. Good luck!

**Comment by NiielsP** [comment]
Mmmh, I don't agree with you on some points.

1. I don't believe any ressources should be non tradable. Because the goal of this game is to have a complex economy, with players studying the market and grow the right crop or farm the right ressource to sell it to other players.
This is not an issue because unless you are a whale, you will need to farm at least one ressource to craft a NFT, and buy the rest with the SFL you get from crops, or with the SFL you get from mining. So everyone will have something to focus on.
In your case, for Kuebiko, you still have time to grow wheat until launch, and if you don't have enough, then you can sell alll other ressources, like wood and gold which will be expensive at launch, so you can buy the remaining wheat. By the way, getting multiples farms to grow wheat is an great investment. It cannot be made for free in a decent period. And you will always have whales against you when you aim for the best NFTs in the game, either it's a whale that has 10 accounts or one that has 1 account but more cash. 
By the way, everyone has 1 account only for now, the ones that have more are getting banned. So you are fine

But I do agree on the fact that having a level requirement for NFT is a good idea, this way a minimal commitement into one's account is required so the NFT can be acquired. 


2. I don't understand why you want to introduce a more complex craftng system. Burning SFL is made to stabilize the token, but once SFL has been burnt into wood, stone, etc, it doesn't matter anymore to consume more ressources, it just makes the NFTs more expensive in ressources, so better to just increase the amount of ressources needed to craft an NFT.

But if you see the wood being refined into planks (or other ressources) as a feature, it is very interesting and i'm all for it. We would get closer to a MMORPG and I love that

**Comment by JacobSobolev** [comment]
There will be a limit on multiple accounts. Currently it seems like 5, maybe when this option will be permitted it will be lower
