### ISSUE TITLE
BrightID

### ISSUE THREAD

**Issue by dfsplus** [sunflower-land/sunflower-land#530]
I propose to use BrightID to identify the situation of a single user, because many people have multiple accounts of Discard. BrightID lets apps make sure their users don't have multiple accounts so that everyone has a fair share and a better experience. Gitcoin has used it for validation.  I think BrightID  is a good way to avoid  one person with multiple accounts, please think about it.
https://www.brightid.org/

**Comment by Aminbtdds** [comment]
Juat read their whitepaper, cool project, but needs player side participation way more than discord verification, imho, with global "Lack of reading" problem which we can see obviously in our discord for sure too(people repeatedly asking questions which their answers are already in announcements or faq channels), it will be so hard and frustrating for both players and support team to implement bright id instead of discord verification. 
I guess analyzing and filtering fingerprintjs data to find abusers and ban them would be more practical.

**Comment by adamhannigan** [comment]
@dfsplus This looks cool. I haven't seen it before. 

There are a few 'proof of human' projects out there. I will give this a deep explore 🤗

**Comment by HoxNiky** [comment]
brightID or Civic

**Comment by HoxNiky** [comment]
brightID or Civic

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
