### ISSUE TITLE
[PROPOSAL] New uses for Decorative Items  + Farm Attributes

### ISSUE THREAD

**Issue by RogGarcia** [sunflower-land/sunflower-land#609]
_*The text has been translated automatically_

Hello, I would like to propose a new mechanic for the game, based on the decorative items like the Sunflower Statue, Potato Statue etc. Creating real value within the game, beyond its aesthetic function.

 - Each decorative item would have a beauty value (from 1 to 10, for example)

- Your farm would have an initial **beauty score of zero**. With each decorative item added to your farm, the **overall beauty rating** would be increased.

- Decorative objects could have other stats to add to your farm besides beauty, such as:
Sunflower Statue (1 beauty / 3 notoriety / 2 fame)

- Your farm's overall beauty rating (or other ratings) could reflect **more tourism, greater notoriety or more fame** for your farm.

- Each of these stats, calculated in relation to the general ranking of all farms, could bring benefits, such as:
**Tourism** (X SFL drops every week)
**Notoriety** (% discount on seeds for 48h every week)
**Fame** ( % profit per harvest sale for 48h each week)

If the guild system is implemented, these statuses of beauty, fame and notoriety could be added to the overall guild ranking bringing other benefits to all members.

**Comment by SrCouve** [comment]
For me, a mechanic like this is extremely important, to generate utility for decorative NFTs, to generate greater appreciation for them and make the market more heated, I had a conversation about it with Romy , and the feedback was positive, one point he addressed was "what if we draw?" and a member suggested that the tiebreaker was the amount of SFL on each farm, I found it interesting even to stimulate the SFL Hold as well, I thought your proposal is very good, I think it's interesting for us to evolve it here,

**Comment by RogGarcia** [comment]
Nice. Well, from your nickname, I think you speak Portuguese, which would make it a lot easier for me, as it's my first language. If you find it interesting, we can develop the concepts collectively and make a more structured proposal here on github. If you would like to get in touch to discuss this proposal, please add "Eremita#6659" on Discord.

**Comment by RogGarcia** [comment]
*The text has been translated automatically
On second thought, I think it is more productive and better to keep the game mechanics more cohesive, focusing on just one attribute of the decorative objects, in this case just beauty or its pair that is tourism.

**How it would work according to what I imagine:**

- Each decorative object would have a beauty level, which can be from 1 to 10;

- Every 24 hours the sum of the beauty levels of each of the objects present on your farm would be computed. As the days go by and when you reach 100 beauty points (just one example), a group of tourists would show up at your farm and stay there for 16 hours. During these 16 hours you could collect a fixed amount of SFL.

- With the appearance of tourists on your farm, the count of beauty points would be reset and the cycle start again.

- The amount to be received in SFL from tourists would be indexed to one of the crops, as an example, we can say that tourists would pay the equivalent of 10 cauliflower in SFL. In this way, this value would always be linked to the halvenings.

**Other mechanics and new items to craft + special NTFS for tourism:**

- Every tourist who visits a place likes to buy a souvenir, so in addition to earning SFL for the "entry tickets", it would be possible to craft new items such as, for example, "souvenir of sunflower land" (100 sunflowers/5 wood/1 gold ).

- These new tourism-related items could only be sold during the tourist event (or at opensea). Another option is that these souvenirs would not be sold by SFL, but would give a percentage increase in the value of the "tickets"

- In addition to souvenirs, there could be other items in NFT to be crafted that would only be used in relation to tourist events, such as a "ferris wheel" that would give a percentage bonus in relation to the value of the tickets, thus opening a fourth area of ​​specialization of the farms, which would be tourism, in addition to agriculture, livestock and the extraction of natural resources.

**Comment by SrCouve** [comment]
![image](https://user-images.githubusercontent.com/98098233/164909176-bcc77861-2c20-4245-b03b-2bb336d6b4bc.png)
Scoring Decoration system:

**_1 Cost in SFL = 1 decoration score_**

(For the sum of the decoration score, the price of the crops taken into account in SFL will always be that of the current Halving, to avoid a change in rank as a result of the Halving)

**_Supply score:_**
1 - 200 = 400 decoration score
200 - 500 = 300 decoration score
500 - 1000 = 200 decoration score
1000+ = 50 decoration score

**_Has a function:_**
0,1x

(As the NFTS with functions usually costs much more SFL and has an assigned function, I think it is fair that they have a multiplier with a very negative weight, this way we will have a fair balance -- as NFTs like scarecrow has benefits in crops, for example, decorative NFTs will have more value in decorative rank, since they are decorative)

**example:**

![image](https://user-images.githubusercontent.com/98098233/164909186-f48fd7aa-968d-48b4-9753-6b78b926d90c.png)
56,41 SFL = 56,41ds
1000+ Supply= 50ds
**106,41 Decoration Score**

![image](https://user-images.githubusercontent.com/98098233/164909195-5abf5d68-db22-4e65-bdc4-8156c8ad2153.png)
32,30 SFL = 32,30 ds
500 - 1000 Supply = 200 ds
**232,30 Decoration Score**

![image](https://user-images.githubusercontent.com/98098233/164909199-699be081-08db-4047-8394-498649246fa7.png)
1348,28 SFL = 1348,28 ds
200-500 = 300 ds
Has function = x0,1
**164,82 Decoration Score**

**Comment by RogGarcia** [comment]
Very cool way to rank items! But I don't think it's interesting for items that already have a passive bonus and a purchase purpose (besides decorative), adding more bonuses beyond their original function, such as scarecrows and beavers. This could reflect negatively on purely decorative NFTs, reducing their in-game functionality.

**Comment by SrCouve** [comment]
if you take a good look at the Nfts with function, they have a multiplier of 0.1x, that is, of the 100% that they would score, they will only score 10% precisely because they already have a function and are already the most expensive

I added you on discord as you asked, my discord is: KaiVictor#0516, if you are interested, we can develop a well-crafted proposal together to present,

**Comment by SrCouve** [comment]
> Very cool way to rank items! But I don't think it's interesting for items that already have a passive bonus and a purchase purpose (besides decorative), adding more bonuses beyond their original function, such as scarecrows and beavers. This could reflect negatively on purely decorative NFTs, reducing their in-game functionality.

f you take a good look at the Nfts with function, they have a multiplier of 0.1x, that is, of the 100% that they would score, they will only score 10% precisely because they already have a function and are already the most expensive

I added you on discord as you asked, my discord is: KaiVictor#0516, if you are interested, we can develop a well-crafted proposal together to present,

**Comment by Kratka007** [comment]
You guys are having great ideas. Congrats!!
I hope that more people can engage in this proposal and so on the devs take a look, because I think the future revolves around what you've been talking about.
This would be an excellent way to prevent decorative NFT's from devaluing, which is exactly what is happening now, due to the great speculation

**Comment by SuperSynapse** [comment]
This is very cool! SrCouve just shared this proposal with me. I think this is a great combo with my proposal! https://github.com/sunflower-land/sunflower-land/issues/781

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
