### ISSUE TITLE
[Offer] Make a purchase of new lands with SFL. It will strengthen the currency

### ISSUE THREAD

**Issue by IvanSkazkin** [sunflower-land/sunflower-land#660]
**Hello.**

Make a purchase of new lands with SFL. It will strengthen the currency

I also sit in many chats and people predict the death of the game if the entrance to the game is unlimited. Many suggest limiting entry, or making it for SFL (50-100+). As well as selling land as boxing. And limited. For example, no more than a certain amount per week. This will create excitement for entering the game and will have a good effect on the economy.

**Comment by DI9QU** [comment]
I firmly oppose setting the threshold to buy land for SFL, because it is a typical scam of capital market! That will cause no new players to enter when the SFL price is too high! We know that sunflower is a game. A game is destined to require players to enter. Only players can have everything. The current mode is just right. If the SFL price is low, you can directly increase the number of holes and start farming. If the SFL price is too high, you can still start farming with 5 holes in the land, so that the game will never lack players! Only players and users have Yi

**Comment by Meowgikarp** [comment]
I believe both Ivan and DI9QU have valid points, and perhaps we can find some middle ground here. What gala games does is to only allow players holding NFTs to cash out, so even though everyone can start a farm land, only those who are willing to invest by buying NFT (i.e. take on more risk vis-a-vis a player who did not pay) will receive monetary reward. Perhaps we can implement this too. However, what is different is that SFL also allow people who did not buy NFT to craft NFT (if they are fast enough and hardworking), so that will encourage free-to-play too. If we have everyone owning land and cashing out SFL, SFL prices will always be under sell pressure, similar to Axie's SLP (which unfortunately never recovered), even with our unique tokenomics.

**Comment by sunfloweroglfg** [comment]
Low barrier to entry is extremely important for new users. I wouldn't touch the 1 matic entry. 

Land expansion is coming for full users. It'll cost some sort of amount. That will strengthen the token along with the current nfts in place.
