### ISSUE TITLE
[PROPOSAL] Goblin Town

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#710]
The purpose of this proposal is to explore the idea of a Goblin Town in Sunflower Land.

**Problem**

1. Players get confused and often lose progress when they are withdrawing items.
2. There is no clear distinction between what parts of the game are off-chain (our game server) and on chain (the Blockchain). As we add more on-chain features, we need a way of making this clear to users.
3. As we add more decentralized features, how do we ensure they don't interrupt and cause issues with out centralized (off-chain) gameplay.

**Solution**

We create a new "Goblin Town" area that a player must navigate to by clicking a button. This area is **not on the current map**, but will appear on a new URL - e.g `sunflower-land.com/goblin-town`

Before navigating to that area, we will provide a clear warning that a user must sync their progress before going to the decentralised Goblin town.

**Human Town (Current map)**

The normal Sunflower Land map will include the following:

- Shop (without the rare section)
- Blacksmith (without the rare section)
- Barn (without the rare section)
- Kitchen

A user will buy/sell items that are recorded on our game server. Minting items and the bank no longer appear on the current game.

**Goblin Town**

The Goblin town will host all of the decentralised actions that a user must take including:

- Blacksmith to mint rare items
- Shop to mint rare crop related items
- Bank
- Tailor
- Wishing Well

Over time we will add more decentralised functionality to this area.

The Goblin land will have a similar HUD, but will not enable a player to save, sync or perform other "off-chain" actions

## Plan

1. Add an entry point to the Goblin Town (i.e. Click on the Menu or ask a Goblin about the town)
2. Accept the modal that warns them to sync any on chain progress
3. Navigate them to Goblin Town
4. Build out the basic Goblin Town map
5. Goblin Bank
6. Goblin Blacksmith
7. Goblin Farmer
8. Goblin Barn Manager
9. Goblin Tailor
10. Wishing Well

**Comment by Netherzapdos** [comment]
Excited for this one 😋 

Are we going to have to design an entirely new map that will resemble a goblin town (maybe cobble roads, lamps, different trees, different landscape, etc.) or will we be just be putting stuff on top of the same map?

If we're going for a new map I think a mountainous region sounds nice, tho I'd imagine that would interact with the lore book from the north 👀

**Comment by tiffanydys** [comment]
Since trading will also be decentralised, I'm thinking maybe we should add it here in Goblin Town as well. Maybe add a sea part on the lower left of the town with a ship. Since it's still in progress we can make a prompt on the ship when they click it. Something like `Goblin Trading coming soon.` or something.

**Comment by Unnamad** [comment]
There's a problem. If we just want to see what the new NFT looks like and its effect, is it going to cost a synchronization? If so, please add a visual listing to the Human City before updating.

**Comment by Driftingwood** [comment]
A great idea, I've been itching to make more goblin art.

**Comment by adamhannigan** [comment]
@tiffanydys Yes, that is the plan. DEX, DAO and other protocols will be accessed through the Goblin area 👏

**Comment by NotKeen** [comment]
I really like the idea to have a special area for doing blockchainy stuff, also to display the NFTs in a better fashion, being able to sort and categorize them better maybe, since there will be more and more coming (many not craftable anymore).

Regarding reminding players to sync before minting something (and also taking @Unnamad's point into account): 
I'd propose instead of forcing players to sync before entering Goblin Town (maybe they only want to check out the NFTs), maybe we could implement some kind of check how much unsaved progress would be lost (maybe even display the SFL / items difference to blockchain) whenever players try to do a mint or something else that would reset progress to last blockchain state. This could also be implemented with the current map already. That could make it much clearer than a big red warning message that many people still ignore haha.

**Comment by adamhannigan** [comment]
> I really like the idea to have a special area for doing blockchainy stuff, also to display the NFTs in a better fashion, being able to sort and categorize them better maybe, since there will be more and more coming (many not craftable anymore).
> 
> Regarding reminding players to sync before minting something (and also taking @Unnamad's point into account): I'd propose instead of forcing players to sync before entering Goblin Town (maybe they only want to check out the NFTs), maybe we could implement some kind of check how much unsaved progress would be lost (maybe even display the SFL / items difference to blockchain) whenever players try to do a mint or something else that would reset progress to last blockchain state. This could also be implemented with the current map already. That could make it much clearer than a big red warning message that many people still ignore haha.

It is a good idea to force them. We can firstly detect if they have any off chain changes and then force them to sync to continue.

It may get a bit annoying if a player did not make changes and is forced to sync

**Comment by NotKeen** [comment]
> It is a good idea to force them. We can firstly detect if they have any off chain changes and then force them to sync to continue.
> 
> It may get a bit annoying if a player did not make changes and is forced to sync

Yeah I mean if players just want to check out the NFTs, they can still do that in the Docs. So I guess forcing players to sync progress before entering goblin town could work, if all the info available in goblin town is also obtainable someplace else.

**Comment by ahh1539** [comment]
I like the idea, just curious to see how it would be implemented. What if it was implemented so that when someone visits `https://sunflower-land.com/play/` they are first brought to a map (pictured below) that has many locations, the main two being `Goblin Town` and `Farmers Town` (could be a better name). Each location on the map would have a button that takes the user to that corresponding location, and the user can at any point return "Home" which would just be the expanded map view. Clicking into `Goblin Town` would still have all the same warnings and requirements as originally proposed but it would visually be nicer to navigate.

Here are the assets we could use to make the map: https://zeshio.itch.io/pixel-hex?ac=qvfLWaeHch
![frVCLb2](https://user-images.githubusercontent.com/31779206/165512571-2157176a-671c-446e-bdbc-55b433f83489.jpg)

**Comment by DeaerCui** [comment]
一个强大可玩性的农村我愿意花费更多的时间来参与

**Comment by JCtapuk** [comment]
I thought it was you, not goblin, because people are at war with goblin =) And here it turns out that people are slaves to goblins =)

**Comment by sfwhat** [comment]
I think I have a solution to the first part of the plan.
Hot Air Baloon that goes to the Goblin Town, 
Purchase one ticket from **_The Aviator Goblin_**, he will take you to their hometown.

![arkaplansunfl (8)](https://user-images.githubusercontent.com/95937808/165544214-30d87ef1-3554-4bbe-93b0-212b2a872e5d.gif)
![arkaplansunfl (7)](https://user-images.githubusercontent.com/95937808/165544215-41943f1b-5b7c-41d2-9872-2ace26c395e3.gif)
![arkaplansunfl (6)](https://user-images.githubusercontent.com/95937808/165544208-4bf15c45-779b-4059-8084-00989cf8f854.gif)

**Comment by ShiningMinions** [comment]
I definitely like the idea of a goblin town, but I highly recommend we laser focus these discussions on the main problem and not get distracted by the potential solution.

### The Problem Summarized:

Players are losing their assets because they don't understand the difference between on-chain and off-chain.

### Proposed Solution:

When I solve problems, I always try to find the path of least resistance to solve it. The goblin town is a super cool idea and would be great content for the game. HOWEVER, is there a simpler solution that can solve the problem at hand?

Alternatively, why not just force players to sync to chain before a withdraw (or any other future state-breaking features)? This would be such a small change that would add tremendous value for the average player.

(i.e.) Instead of the scary red warning text on the withdraw screen, why not instead just have something that says "you must sync on chain before you can withdraw your items", and display the "Sync Now" button? I'm sure you could calculate on the front-end if their game state is out of sync and show them this button.

**Comment by xiaoqiu06** [comment]
These are small problems, he is not a PC game, but a blockchain game. The most important thing now is the consumption of SFL tokens. When the token price is stable, there will be many people participating in the game. When the token price is lower than a lot, the game will lose its vitality, so the most important thing now is how to increase the consumption of the token. is an important thing

**Comment by BlockChainMeta** [comment]
I think this may create more problems than you expect and also provide a bad user experience in some cases.

For example, I've been checking if the golden cauliflower is available each time I go to harvest my crops. There's no need to sync to check this and forcing that just to view would be a terrible experience.

I also generally like to keep an eye on how many of certain rare NFTs like the beaver have been minted without needing to leave the game or go to another area.

The NFTs and "rare" section serve as great incentives to grind for many players. People think, "Oh, I need to collect wood to get a beaver, got it." They see all the possible uses for the harvested crops in the same area where they go to sell things so it's a constant reminder of what they're working toward and I believe this plays a big part in pushing people forward. It also helps them prioritize what to make next depending on which NFTs they choose to go for. Removing this into its own area that has a separate load time and a forced sync may reduce that feeling of striving towards something.

People may say "oh you can read the docs" or "oh they can just screenshot it once" - but look at the discord and see how many people don't read the docs at all. Many of the docs for NFTs also still need to be updated.

I propose that you simply force a sync before a withdrawal if that's the main issue at hand.

As far as the on-chain and off-chain differences, maybe that's not as important to the end user as we think. Maybe the docs is a good enough place for this.

If you were to go ahead with splitting these, I would want a "view-only" mode in the human world that shows the basic info from the goblin word about the NFTs - the costs and how many have been minted. Potentially a single table on desktop which is a summary view.

**Comment by adamhannigan** [comment]
@ShiningMinions We are adding more security to the smart contracts which means that the mint + sync is now separate actions. 

This means that a user would also need to sync before trying to mint a rare item.

We will be adding more smart contract interactions as well. The aim is to try lay down the foundations now before we have too many on-chain + off-chain actions scattered throughout the gameplay and people start inadvertently losing progress if they do not save before.

**Comment by ShiningMinions** [comment]
@adamhannigan thanks for the response - just a few of my follow-up thoughts 😊.

If I'm hearing you correctly, you are wanting to add more on-chain/off-chain actions - but the fear is that this consequently leads to more "progress lost" situations for the end player (because they aren't syncing to chain at the proper times).

Since I'm developer, I like to talk in psuedo code. I hope this line of thinking helps solve this problem:

### What I think we should do is this (laying the foundations, as you say):

1. First, determine all of the "on-chain" actions a user can take in game (i.e. withdrawals, future minting, etc.)
2. Second, determine all of the "off-chain" actions a user can take in game (i.e. harvesting crop, buying seeds, mining gold, etc.)

### Once you figure out which actions are "on-chain", now here's the logic:

1. Determine if there is any new "off-chain" state introduced since the last sync (harvested crops, new gold, etc.).
2. If there is indeed some new "off-chain" state, then don't let the user perform the "on-chain" action (withdraw, future mints). Instead, show the user a message: "You must sync to chain before you can perform this action" along with a "Sync Now" button. After the sync completes ONLY THEN it will reveal the "on-chain" action (withdraw, future mint).
3. Otherwise, if there IS NOT any new "off-chain" state introduced since the last sync, then allow the player to perform the "on-chain" action immediately.

I hope this is helpful, and I hope that I'm understanding everything + on-par with what you need. Cheers!

**Comment by Abidox808** [comment]
> I propose that you simply force a sync before a withdrawal if that's the main issue at hand.

**Comment by adamhannigan** [comment]
@ShiningMinions Thanks for the idea, I believe these are a great solution for our current problem but it would face some issues once we scale and just keep adding these items in the game. Before we know it, more than half of the game would just be disabled buttons 😅 

There are some stronger concepts around the DAO + DEX that we think a decentralized playground would help with. 

What we are trying to do now is lay the foundations of where we see the vision of the project. You may not even need a farm if you want to interact with the decentralised marketplaces, dexes etc. 😄

**Comment by d4nnY132** [comment]
Goblin Builder

![Goblin Builder](https://user-images.githubusercontent.com/67920456/165717552-819c90a5-a419-438b-9aa3-4b8358600585.png)
![Big Goblin Builder](https://user-images.githubusercontent.com/67920456/165717559-43c93c3e-8972-45e2-8349-42b84f4ab2f8.png)

**Comment by brian-man** [comment]
> 2. Accept the modal that warns them to sync any on chain progress
This should just auto-sync if needed, like (hopefully) Withdraw is becoming soon.

**Comment by SrCouve** [comment]
![mage goblin](https://user-images.githubusercontent.com/98098233/165759669-dc8ecb8c-b33f-4ed7-8ce5-92569da91266.gif)
![mage goblin (1)](https://user-images.githubusercontent.com/98098233/165759676-93ac4261-0460-48be-9b1c-5ad78d90975d.gif)
![mage goblin (2)](https://user-images.githubusercontent.com/98098233/165759680-ed87dde7-4aea-4670-8c53-fd6499361e9a.gif)

**Comment by ShiningMinions** [comment]
@adamhannigan my closing thoughts:

> @ShiningMinions Thanks for the idea, I believe these are a great solution for our current problem but it would face some issues once we scale and just keep adding these items in the game. Before we know it, more than half of the game would just be disabled buttons sweat_smile

Got it 🙂 - my closing thought here: I would highly recommend thinking about solving the short-term problem today, even if it leads to some scalability issues in the future (and who knows, maybe it wont? new things will be learned along the way). Solving this problem today is simply too valuable to wait. Code can always be tweaked in the future, but I don't think players can wait much longer for this problem to be solved - losing game progress is pretty painful.

> There are some stronger concepts around the DAO + DEX that we think a decentralized playground would help with.

Sounds good - with your specific example of the "DAO and DEX" problem, I couldn't agree with you more - I think a completely separate decentralized playground is **perfect** for use-cases like these (AKA: use-cases which have high-frequency on-chain interactions). Goblin town seems perfect for that.

> What we are trying to do now is lay the foundations of where we see the vision of the project. You may not even need a farm if you want to interact with the decentralised marketplaces, dexes etc. smile

I think it's very good to think about foundation. Your vision is eons ahead of what me or any other community members are thinking about - so guaranteed we are not seeing the bigger picture like you are. However, and FWIW, over the years as a dev I've learned to live by this philosophy: Don't solve problems which don't yet exist. I've seen so many times IRL where clients "think" they will have some future problem and try to solve it preemptively. Over time the problem either become obsolete, or the preemptive solution misses the mark completely. It's a "we built the best ladder, only to discover it's leaning against the wrong building" scenario. There's simply a ton valuable information that will be incrementally learned over time from the community, which can completely alter what we think the solution is today. Just food for thought, and you probably are already thinking this way.

Finally, just want to reiterate - I love the goblin town idea as content, and I simply love this game you've created. I just want to contribute my voice and support the team however I can. Nothing but positive vibes from me ❤️. Cheers mate.

**Comment by baron** [comment]
I guess I'll chime in with my 2 cents.

Problem: We want to keep the game flow while minimizing the loss of progress by users when they initiate withdrawal

Sub Problem: It is currently hard for users to distinguish the onchain state and in-game state without taking mental notes

Possible Solutions

- Bundle a syncing operation to precede the withdrawal so that it becomes "sync and withdrawal" on the backend
- Show a diff of the in-game progress and on-chain balance so that users can visualize their possible loss before initiating the withdrawal transaction

**Comment by SrCouve** [comment]
![Uti go mage](https://user-images.githubusercontent.com/98098233/165797275-5d583243-5780-4cdc-b78c-3322037206ff.gif)
![Uti go mage big](https://user-images.githubusercontent.com/98098233/165797285-04bcdb8b-37fc-4bbf-a456-565a72b78bdd.gif)

**Comment by SrCouve** [comment]
![ulti](https://user-images.githubusercontent.com/98098233/165801500-e5bd3708-54a2-42b4-be23-a86c33f55224.gif)
![ultibig](https://user-images.githubusercontent.com/98098233/165801511-f9935c7c-a858-487d-a3ff-9efa8a6f832d.gif)

**Comment by brian-man** [comment]
Does the discord "Choose your Side" choice have any impact on the player experience with Goblin Town? If so, that post in `#role-assign` should mention that.

**Comment by adamhannigan** [comment]
@brian-man There will be some gameplay elements + Easter Eggs in the Goblin town based on the side you choose.

**Comment by Z1kou** [comment]
Alright took me a while but I am not gonna miss all of this ! First of all I believe that the Idea is genius, What we have with SFL is something truly marevelous, Being able to teach the average Person about the crypto world in a fun gamified way, as we are opting for building an actual brand and scale the game properly, I believe we need to look at this very carefully, We are exploring here uncharted grounds and i would like for us to sink some core values/Idea's as we are delving into this:


1-We are opting for a broader player base (from children to grown up) that may have 0 information about crypto and any of the on/off chain data, and that honestly wouldn't care about these complicated stuff because all they want is to play the game for fun (Which is our goal !)

2-We need a seemless player experience when playing the game that would keep them immersed in the game even when doing on chain actions such as syncing !

3-We need to understand what makes the game interesting on all of us, (This might differ from player to player, for me its the simplicity) And keep that in mind while adding new features such as the Goblin Town

4-Ensuring its not abusable by the naughty guys

5-We need to add The sherrif  for mind peace of the people! 



Let's now apply these values to the Goblin Town:


-ensuring that the average player uses all the features of the game without any hardships is a must, The goblin Town Is amazing to ensure separation of off/on Chain data, and thus should be tied to the game in a manner that will  seem smooth,(Example having to switch between maps by signing a transaction when you want to sync in goblin town is a non smooth game transition),Without spending too much on educating the player by letting him read(THEY NEVER READ) Opting for a tutorial in which they interact with the town and understand by experiencing the transactions is a must for me  !

-Adding a few cool little addition to syncing actions to "Gamify" this newly concept of crypto gaming for new players, this could be done by adding a animation for when you mint the item with a little sound effect that  is similare to what all games play when u unlock a treasure chest (Example: if you mint a carrot sword, when the transaction gets approved, you get a farmer lifting the carrot sword in the air with a cool sound effect, This should be applied to all items, it will be hard to maintain this format with new NFT's release but it will add so much detailing that differentiate a well sculptured game than others!)


I will stop here now as i don't want to make this message longer, Thanks for reading and have an amazing day everyone !

**Comment by NotKeen** [comment]
@adamhannigan 
> You may not even need a farm if you want to interact with the decentralised marketplaces, dexes etc. 😄

This is a cool idea and a really strong argument for separating Goblin Village from the main land. For example in v1, I provided liquidity from my ledger account, and didn't even had a farm there (imagine confirming on ledger for every cauli harvest haha).

Now in v2, there may also be people who just want to LP SFL and stake in the wishing well, or who want to mint NFTs with just bought resources instead of self-crafted ones without even wanting to own a farm and play the game, and I think that should be encouraged (as long as it is a net-win for the game).

**Comment by Alexcnder** [comment]
Just swapped the Tailor with a goblin and made the sheet in goblin colors

![new tailorspr_idle](https://user-images.githubusercontent.com/87881787/167220069-5ee5f46f-0475-4762-8e46-dba0fed2c7a6.gif)
![export new tailorspr_idle-export](https://user-images.githubusercontent.com/87881787/167220101-f11652d9-2048-4823-a0ff-2ef3282e8d73.gif)

**Comment by newb23** [comment]
Popping in a note saying this can be updated/closed. <3
