### ISSUE TITLE
[IDEA] Crop Halvening

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#722]
The purpose of this proposal is to explore how we can reduce inflation of crops and ensure they remain scarce for future gameplay.

**Problem**

We have an infinite supply of crops which will make crop prices extremely low on secondary markets. This will lead to an infinite supply of crops which can damage gameplay and future NFTs which could require crops.

**Proposal**

This idea is still very fresh and would love to play out some implications with the community.

Instead of halvening seed prices and crop sale prices during the halvening periods, we halve the crop rewards. Instead of planting 1 seed and receiving 1 sunflower, you plant 1 seed and receive 0.5 Sunflower. Crop sale prices remain the same throughout the halvening periods

Based on this pattern, in the future you would receive 0.00025 Sunflowers. This will essentially push the Sunflower Supply to a soft limit as rewards lessen and lessen.

**Cons**

The downside of halvening the rewards is the confusion it could cause new users. It may appear strange if you plant a Seed and receive 0.000025 Sunflower

**Comment by Labochi** [comment]
I do love this kind of idea. If the problem is for new player, I think it's not a big deal, they can always be educated.

**Comment by brian-man** [comment]
> Instead of halvening seed prices and crop sale prices during the halvening periods, we halve the crop rewards.

Clarification request....

Today
1. seed prices halved
2. crop prices halved

Proposal
3. crop yield halved
4. remove 2
5. remove 1?

Are you including 5 as well or not?  If not, then after 2 halvings farming is a negative SFL activity.

**Comment by j923sneaks** [comment]
> > Instead of halvening seed prices and crop sale prices during the halvening periods, we halve the crop rewards.
> 
> Clarification request....
> 
> Today
> 
> 1. seed prices halved
> 2. crop prices halved
> 
> Proposal 3. crop yield halved 4. remove 2 5. remove 1?
> 
> Are you including 5 as well or not? If yes, then after 2 halvings farming is a negative SFL activity.

agree. new farmers wont keep up with the buy prices if buy prices are not halved too

**Comment by eggc95** [comment]
Instead of doing this and destroying the current system in place, like @brian-man said crops farming will become a negative activity which is not what is wanted, instead of that we combine two ideas together to achieve this by not allowing crops to be sold as SFL straight.

Here's my idea, you have to craft food to sell it as SFL as for the balancing it has to be net positive no matter what to ensure that new farmers get to earn something. 

Example using current seed price/sell price:

Roasted Sunflower sells for 1 SFL. requires 1000 Sunflowers. right now it will cost 0.5 SFL to craft.
Next halving will still cost 0.5SFL still as both seed prices and crops yield are halved. ensuring always positive returns except double the time/effort required to farm. 

This essentially solves crops rarity as people should be selling Roasted sunflower instead of crops and it will be worth more or at least the same each halving.

And this solution shouldn't affect any system in place as SFL supply increment should slow down after each halving yet still increasing scarcity of the token itself. also solves the issue of using crops as NFTs requirement.

**Comment by Punksnot** [comment]
The idea was great it should be done asap.. because of the halvening the price of the crops went down.. and the market is not alive

**Comment by MarketParticipant** [comment]
The shop in the game creates a floor price for crops because if the price
on a secondary market falls below the shop's price minus fees, it makes
sense for people to arbitrage it buying it on the secondary market and
selling it to the shop.

Resources (wood, stone, iron, gold) and animal products (eggs in v1) do not
have a floor established by the shop in the game so their prices rely on
demand driven by soley NFTs.  The only way to support their prices is a
constant flow of NFTs or the shopkeeper deciding to convert them to SFL.

Since crops have a conversion rate to SFL determined by the game, the real
issue is that infinite crop emissions will translate to SFL eventually
approaching zero.  I think the game needs more sinks that don't increase
crop/resource/SFL emissions.  For instance:

   - NFTs that boost experience points.
   - Upgraded buildings and fences, alternative base map "skins", etc.
   Fortnite has an income of $25-30/user/year selling skins with no boosts.
   - Player profiles to personalize the game and increase social
   stickiness.  Instead of just farm #, let a player enter their name and a
   short twitter-like tagline about themselves.  Eventually add a profile pic
   and an in-game chat rooms gated by holding certain NFTs that cost
   crops/resources:  chicken farmers guild, wood ents, goldbugs...
   - Lottery.  Every week players enter some amount of crop/resource and
   the lucky winner gets 10X what they put in, but the losers burn
   substantially more than that.
   - Leaderboards.  For some reason it makes me happy when I am in the top
   10 holders of a crop or resource.  Leaderboards will encourage hoarding,
   which is healthy for the game economy and price of SFL.

**Comment by PedroAugusto-BCS** [comment]
an alternative is a constant burning system

something like an evil goblin that makes all your crops produce less until you get X from a specific crop

Farmers will keep part of their production in stock to quickly solve the problem with the evil goblin

with the nfts, the burning could be turned to the crops that has the most supply at the moment

would make the game more dynamic

**Comment by xiaoqiu06** [comment]
If we can't solve the problem of scarcity of sfl, but keep releasing the land, I believe that our game is getting closer and closer to V3. This is something that all supporters don't want to see.

**Comment by xiaoqiu06** [comment]
> 以免对新人造成任何陌生感。您可以增加生产 NFT 所需的数量，而不是减少产量。
> 
> 如果我们进行计算，我们会发现每天的作物产量没有变化。这直接影响资源的价格和一般的 nfts。因此，正确的做法是根据制造 NFT 所需的数量减半来增加。
> 
> 来自种植园的资源 = 减半乘数 2x 采矿资源 = 减半乘数 2x
> 
> [减半除数不一定与资源除数相同]。
> 
> 例如：南希
> 
> 小麦 100 >> 200 SFL 20 >> 10 木材 50 >> 100
> 
> --> 这样，随着时间的推移，我们对工具、nfts 和资源的估值会更高。
> 
> 时间越长，制作相同的 nft 所需的资源就越多，而新的 nft 将需要更多基于先前 nft 的资源。
> 
> 关于命名法，当值增加太多时。例如 10k 小麦。它可以更改为“PACK OF WHEAT”或类似的东西。
> 
> 例如：1 PACK 包含 1k 小麦。
> 
> 作物生产可以通过 Boosters 的 NFT 来控制。通过启动增加某种植物/增加掉落/减少收获时间的 Nfts。
> 
> 也可以添加未来的季节和害虫。这会影响农作物并降低资源产量

Increasing the number of NFTs cannot fundamentally solve the problem, as can be seen from the current NFT sales. If you want to increase the scarcity of SFL, you need to make the current crops not directly exchangeable into tokens, and have another form of synthetic materials to exchange. At the same time, increase the leaderboard, hold the number of NFTs and farm points to get rewards, so as to make players willing to mint NFTs. Another important point is not to open up and mint new land, because our system cannot share the total output. On the one hand, there is a reduction in production in the game, while the lack of land casting has been increasing on the outside of the game. This is contradictory, very contradictory. incomprehensible behavior

**Comment by StockSavage** [comment]
Is this a problem that we really need to solve? This was very casually dropped as a proposal for something that's so serious. With the amount of money we're playing with, you guys really need to hire an economist before making these decisions.

 No one wants the game to flop but these are the kind of dangerous decisions where you need to know exactly what you're doing and have tons of market data available to make this decision. I wouldn't even feel comfortable answering this question.

**Comment by agcm19** [comment]
mini-game in which farmers will have to trade their crops to gain access.
the reward can be resources/axes/gold 
I think crop price in the secondary market will somehow increase cause another demand is created for it

option 1: crop to sfl
option 2 crops to resources (RNG)
option 3: payment for saving progress (each progress saved burns a crop of your choice)

just create another demand for crops

**Comment by adamhannigan** [comment]
Thanks for the feedback everyone. Just for clarity, this is a very fresh proposal with no plans to implement. The purpose of this discussion is to explore the implications of a decision like this on the game, it is not to make a decision.

There will definitely be sinks for SFL including NFTs, gameplay + land expansion.

The centre of this discussion is around the inflation of crops and whether this is an issue of the game. There are some great ideas around the production of SFL, but they don't quite address the discussion.

To bring some focus back, I think we should address?

1. Is crop inflation an issue?
2. If so, how can we prevent crop inflation?

**Comment by Aminbtdds** [comment]
Imho, Crop inflation won't be an issue if seed price dynamically would be set relatively to crop price at 3d party market.

**Comment by agcm19** [comment]
> Thanks for the feedback everyone. Just for clarity, this is a very fresh proposal with no plans to implement. The purpose of this discussion is to explore the implications of a decision like this on the game, it is not to make a decision.
> 
> There will definitely be sinks for SFL including NFTs, gameplay + land expansion.
> 
> The centre of this discussion is around the inflation of crops and whether this is an issue of the game. There are some great ideas around the production of SFL, but they don't quite address the discussion.
> 
> To bring some focus back, I think we should address:
> 
> 1. Is crop inflation an issue?
> 2. If so, how can we prevent crop inflation?

put shelflife in crops? just like in real life crops do not stay fresh unless...
introduce new NFT that will prolong/extend crop life

**Comment by Muddshoe** [comment]
> Thanks for the feedback everyone. Just for clarity, this is a very fresh proposal with no plans to implement. The purpose of this discussion is to explore the implications of a decision like this on the game, it is not to make a decision.
> 
> 
> 
> There will definitely be sinks for SFL including NFTs, gameplay + land expansion.
> 
> 
> 
> The centre of this discussion is around the inflation of crops and whether this is an issue of the game. There are some great ideas around the production of SFL, but they don't quite address the discussion.
> 
> 
> 
> To bring some focus back, I think we should address:
> 
> 
> 
> 1. Is crop inflation an issue?
> 
> 2. If so, how can we prevent crop inflation?
> 
> 
> 
> 

If the crops become less and less valuable because of inflation, what difference would it make to average farmers if you reduced this inflation but made it harder for them to acquire said crops anyways? Like, what difference does it make if...

1 Day = 1 Radish = 1$ becomes 1 Day = 1 Radish = 0.5$ (Normal, current setup), **2 Days = 1$**

VS

1 Day = 1 Radish = 1$ becomes 1 Day = 0.5 Radish = 1$ (Proposed setup), **2 Days = 1$**

In either case, post halvings, it would take you 2 days to earn a dollar. That's just how halvings work. Unless *you hoard*. Is that the desired outcome? Instead of HODLing the token people now start HODLing crops, which I'd argue is an even more complicated and somewhat perplexing gameplay pattern.

Either system rewards whales since their assets become more and more valuable. If there's no big difference either way then I don't see why there's a need to change? Not only would it screw over most players while simultaneously rewarding people who have been buying and hoarding crops in the P2P marketplaces. This would be problematic because the team thus far has taken a stance against P2P trading, and this change will reward players participating in those trades moreso than the current system does. And since the proposal is already live on Github, any savvy P2P trader will hold their breath and hold their crops to see what becomes of the proposal.

I don't think that crop inflation a problem. I think that crop inflation was always going to be the direction the current system was going towards, and I think that that is okay (and that if the devs did think it is a problem should have been addressed much earlier like before trading was allowed). I would prefer that the team seek a different method of addressing this "problem" rather than fundamentally changing probably the main feature of the SFL token.

**Comment by PigaPigaPiga** [comment]
> > Thanks for the feedback everyone. Just for clarity, this is a very fresh proposal with no plans to implement. The purpose of this discussion is to explore the implications of a decision like this on the game, it is not to make a decision.
> > There will definitely be sinks for SFL including NFTs, gameplay + land expansion.
> > The centre of this discussion is around the inflation of crops and whether this is an issue of the game. There are some great ideas around the production of SFL, but they don't quite address the discussion.
> > To bring some focus back, I think we should address:
> > 
> > 1. Is crop inflation an issue?
> > 2. If so, how can we prevent crop inflation?
> 
> put shelflife in crops? just like in real life crops do not stay fresh for long unless... introduce new NFT that will prolong/extend crop life

in my opinion that was already the way things were implemented to be feeling/looking like as it is right now.. 
1. farmers start farming collecting crops they can sell while fresh or keep
2. farmers who chose to keep their stock of Crops through halvings end up with "less fresh crops", that used to be worth more .. however they have way bigger stocks of them, which may be used for crafting NFTs

> > Re the intial/overall proposal here

Overall I don't like this proposal at all, for multiple reasons:
- It meddles with the very most core functionality of the game, which is the halving mechanic of our $SFL token
- It tries to fix an oversupply of Crops on secondary markets by removing the biggest incentive to turn our Crops into SFL? That seems counter-productive. Crop-price halving is already the main driving force in both driving Crops into SFL and making sure our SFL supply continuously/steadily progresses and grows.
- - Having Crop produce half instead of it's sale prices, would remove all incentive from stocking anything else by Crops (as it'd be the most secure/baseline thing funding everything else -- which is otherwise SFL now and should probably continue to be so)
- - The only reason why there's an over supply of Crops on the secondary P2P trading markets right now, is because the $SFL token itself isn't withdrawable. If and when the token becomes withdrawable, and the factor of "ease" of simply selling the Crops into $SFL for them to be sold directly into a pool, then I believe the oversupply of Crops on the secondary markets would also quickly diminish. **(IF it's prices halving, and not the crop produce that is. Otherwise crops would be king, and the liquid oversupply of Crops would come even more out of control)**
- - - The main worry/concerns about the "oversupply" of liquid crops is regarding future NFT crafts and recipes.. This proposal would make that situation much worse though. 
As it is people are incentivized to sell their crops before halvings, which naturally pushes towards/causes a reset of the liquid crops around the markets, and influences farmers to stack up as much SFL when they can (as they should), while it's worth more.. This is a great design we already have.
If this proposal went through, it'd be infinitely much harder and widen the divide between whales and new farmers in the future to come way more than it already is, because the "proof of work"-aspects of having to farm up the crops yourself, would end up becoming extremely hard manually (you can't reasonably farm up 100 Cauliflowers if harvesting 0.005 Cauliflower at the time) .. 
- - - And my last point against this proposal is regarding the "Thematics and story" of the gameplay as you already mention in the initial cons, where I agree it offers way better new future user experience to always as a baseline to be producing (1) crop from each harvest, and have certain crops just not sell for that much token.. Rather than join the game in 6 months or a years time and be harvesting 0.025 of a token and be faced with the fact that one is very late, every time one tries to harvest a plant 🤔🙈

**Comment by PigaPigaPiga** [comment]
perhaps another consideration would be to add some sort of "tax/fee" to withdrawing (especially for crops and axes). As it is right now (and as it also seems to be looking going forward), 99% of farmers would likely just withdraw most their assets/farmings via either Crops, Axes or Materials (Wood/Stone/Iron/Gold) to evade the SFL-Withdraw-Taxes.

How do we plan to handle that issue? That seems to be a defining and underlining issue regarding this whole discussion first of all..

If $SFL is somewhat reasonable to withdraw compared to them, and it's unfavorable to stock up/hoard resources (which also disturbs the future NFTs using resources crafting-races/games) due to the halving mechanics, then we wouldn't have an oversupply of circulating crops at all.. As transfering crops shouldn't generally make that much sense (imho).

Perhaps it could cost  50 Wood or 1 Gold to withdraw every 100-500 Crops? Something in those lines could be a possible solution, that'd funnel more withdraws/value through $SFL withdraws, fuel taxes and level the playing field (while putting hard-working self-upgrading farmers rightfully at an advantage themselves .. over multi-accounters, botlords and whatnot else out there) 🤔💭

**Comment by adamhannigan** [comment]
There has been some great feedback on this discussion 👏 

Special thanks to everyone who ripped the idea apart 🤣 For now the sentiment appears to be against this proposal. 

It is worth noting, that a proposal being raised does not always reflect the team's opinions. An issue is just a more organised means of discussion than Discord.

We will consider it rejected 🚫 

I will keep this proposal open for a few more days to accomodate any other interesting perspectives.

**Comment by JCtapuk** [comment]
> There has been some great feedback on this discussion 👏
> 
> Special thanks to everyone who ripped the idea apart 🤣 For now the sentiment appears to be against this proposal.
> 
> It is worth noting, that a proposal being raised does not always reflect the team's opinions. An issue is just a more organised means of discussion than Discord.
> 
> We will consider it rejected 🚫
> 
> I will keep this proposal open for a few more days to accomodate any other interesting perspectives.

Well, you can implement an increase in the number of stacks of seeds since for synchronicity 0.1 MATIC will not cover the price of the sunflower and then everywhere else is not possible to cover. To avoid this Halving increases the amount of seed pile in the store and the purchase and sale price is reduced by half...

**Comment by stsvenlau** [comment]
SFL rewards are based on the **total supply** of the token now.
If SFL rewards were based on the **total supply -  burnt** of the token now, I think all the problems will be solved.

**Comment by NotKeen** [comment]
Honestly I think this is a good idea and I think many people are against it because they maybe don't understand it fully. Let me re-phrase how I understand the idea, maybe it helps clarify:

We would basically keep the tokenomics the same as right now, we would just move the halvening mechanism to another place. 
Instead of halving sell prices, we would just halve the amount of yield per seed, which would amount to the same halvening outcome (measured in SFL generation).

Example how I understand it with fantasy numbers: 
Before halving you buy 1 Sunflower seed for 1 SFL, with that you can grow 1 Sunflower. 1 Sunflower sells for 2 SFL. 
After   halving you buy 1 Sunflower seed for 0.5 SFL, with that you can grow 0.5 Sunflower. 1 Sunflower sells for 2 SFL. 

I think this has some side-effects:

1. People don't need to worry about selling their crops before halvings, because 1 Sunflower would still sell for the same SFL after each halving (constant crop prices).
2. NFTs with Crop inputs would have constant SFL crafting value (this could also be a downside if the boost usefulness is affected by halving - scarecrow comes to mind)
3. Food recipe Crop input may need to be halved to keep the balance

**Comment by NotKeen** [comment]
Honestly I think this is a good idea and I think many people are against it because they maybe don't understand it fully. Let me re-phrase how I understand the idea, maybe it helps clarify:

We would basically keep the tokenomics the same as right now, we would just move the halvening mechanism to another place. 
Instead of halving sell prices, we would just halve the amount of yield per seed, which would amount to the same halvening outcome (measured in SFL generation).

Example how I understand it with fantasy numbers: 
Before halving you buy 1 Sunflower seed for 1 SFL, with that you can grow 1 Sunflower. 1 Sunflower sells for 2 SFL. 
After   halving you buy 1 Sunflower seed for 0.5 SFL, with that you can grow 0.5 Sunflower. 1 Sunflower sells for 2 SFL.

So you still halve the SFL you can generate per time span, but crop prices are constant. 

I think this has some side-effects:

1. People don't need to worry about selling their crops before halvings, because 1 Sunflower would still sell for the same SFL after each halving (constant crop prices).
2. NFTs with Crop inputs would have constant SFL crafting value (this could also be a downside if the boost usefulness is affected by halving - scarecrow comes to mind)
3. Food recipe Crop input may need to be halved to keep the balance

**Comment by stsvenlau** [comment]
> > SFL rewards are based on the **total supply** of the token now. If SFL rewards were based on the **total supply - burnt** of the token now, I think all the problems will be solved.
> 
> v1 (SFF) worked like that. Doing it that way had a number of problems. It was intentional to change it for v2 (SFL).

Sorry, I'm a new player.
I have a idea.
All prices remain constant(I mean no halvening), but goblin will attack farmers who have higher output. Rich farmers have to spend more SFL on crafting denfensive items to protect their farms, or buying materials to repair their farms.
This means the richer you are, the more SFL you have to spend on defending and repair work.

**Comment by xZ3D** [comment]
Sorry, new here. 

Why not look into introduce a form of seasons where you can only grow certain crops during certain seasons?

This would allow for periods of time where people would be unable to grow certain crops and the overall stockpile can go down as nfts will still require them to create.

**Comment by adamhannigan** [comment]
Just for clarity, we will start using the **[IDEA]** tag instead of **[PROPOSAL]**. 

The purpose of this Github issue was to explore the idea and the implications, instead of planning to implement or not
