### ISSUE TITLE
[REQUEST] Contributor Credits

### ISSUE THREAD

**Issue by adamhannigan** [sunflower-land/sunflower-land#746]
Sunflower Land is extremely grateful for all of the artists and developers that have helped out the project. We provide accreditation in secondary markets like Open Sea, but we want more players to be aware of the amazing work that is being done.

**Town Hall**

You may of noticed a new building is currently being developed. The Town Hall will showcase community activity and of course our amazing contributors.

It will give the chance for other farmers to see your part in the project and even **visit your farm** and give you a **donation**

**Requirements**

You must of contributed something to the project that has been **used in game**:

- Code
- Art
- Idea

## Request

It is entirely optional to show yourself in the credits. If you do wish to join the credits reel, please provide the following:

1. Your name (can be pseudo anonymous)
2. A social media link (Twitter, Github or Discord)
3. Short bio - **50 characters max** > worth mentioning what you are proudest about building in the game
4. Your Farm ID (will be used to visit and donate to your farm)
5. An avatar - choose from the list below (more will be added)

Goblin: ![goblin](https://user-images.githubusercontent.com/11745561/166076923-68313b8d-66fe-4fac-88dc-b8061c443932.gif)
Farmer 1: ![idle](https://user-images.githubusercontent.com/11745561/166076936-7dca7a48-50e2-4d2b-a2a9-fcc6fdcee990.gif)
Farmer 2: <img width="26" alt="Screen Shot 2022-04-30 at 8 35 50 am" src="https://user-images.githubusercontent.com/11745561/166077059-1fe10558-9e4b-49aa-a95a-b7f027e43a71.png">

An example

<img width="473" alt="Screen Shot 2022-04-30 at 8 29 38 am" src="https://user-images.githubusercontent.com/11745561/166077114-aa9ee5fb-36ed-4fe3-a8d0-d6e9ee71d2ff.png">

# Submission

This Github issue is just for visibility. **Do not submit details publicly here**

Please fill in this Google Form - https://forms.gle/w9V5XMaDRFN1XJNg7

**Comment by InuBakaBo** [comment]
Your name: InuBakaBo
Discord: InuBakaBo#9769
Farm ID: 57
Avatar: ![166076923-68313b8d-66fe-4fac-88dc-b8061c443932](https://user-images.githubusercontent.com/98318794/166078501-955e3613-16df-44cd-88a6-e3bd55366085.gif)

I have been around with Sunflower Farmer/Land almost since the beginning, which was around Oct 2021. Helping out in Beta v1 to implement the first NFT, Sunflower Statue. Watched it grow organically with an amazing team and community that felt like a family, while brainstorming ideas such as the Withdrawal Tax. Being a background investigative detective to hunt down exploiters such as the Iron Pickaxe exploiters, "Cauliflower Cartel" and "Carrot Cartel".

(sorry went over 50 words, I'm just so passionate about Sunflower Land haha)

**Comment by adamhannigan** [comment]
@InuBakaBo Love it! ❤️ 

You may of missed it, but we are collecting submissions for this in the Google Form attached ;)

**Comment by ShiningMinions** [comment]
Is there a deadline to submit by? I'm wanting to add a few more game features before I submit ;)

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
