### ISSUE TITLE
[PROPOSAL] Lucky Gnome

### ISSUE THREAD

**Issue by DonPablo69** [sunflower-land/sunflower-land#765]
Hello I have an idea proposed about the gnome of v1 I find it a pity that it is useless at the moment when it was to influence the weather:
-I would therefore like it to influence our chance of obtaining resources such as precious stones for example to join your ideas of allowing us to obtain diamonds by mining, the gnomes could influence the chances of obtaining diamonds for example .
-The gnome could also allow us to obtain more seeds as rewards depending on the season, for example, given that according to legends they keep treasures.
What do you think about this ? I am open to your ideas.

**Comment by SuperSynapse** [comment]
It was supposed to control the weather in the prior version. I'd really like to see that still get implemented as something that can boost your crop's production

**Comment by DonPablo69** [comment]
nice <3

**Comment by vrillx** [comment]
Im against any NFT tagged as decoration becoming utility nft overnight ... if it does happen then it should be added to nft store ingame again 1000 units..to make it fair towards everyone..some people spend money on deco nft some spend money on utility nft ..if you start bluring the lines between whats what .. it will basically equate to having to craft all nft ..utility or not , because WHAT IF in the future someone decides to add utility to it ?...

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
