### ISSUE TITLE
idea: make it so that multi-accounts don't make economic sense.

### ISSUE THREAD

**Issue by RickFaker** [sunflower-land/sunflower-land#785]
idea: make it so that multi-accounts don't make economic sense.
There are two people: the first has one large farm and has expanded it to 66 beds, and the second person who has three accounts with 22 beds each.
Both the first and second player are attacked by goblins, and in order to defend their farms, they need to craft food for the warriors. The price of the food is equal to the maximum possible profit from the 22 beds (right now it's about 8-10 coins). But the peculiarity is that the first (honest) player only needs to scrap one food to protect all 66 beds. the second (not honest) has to make 3 food, 1 for each account. in this case, multi-accounts become useless and will force players to expand their lands.

I apologize to the developers if this was their intention. But I decided to write it here just in case, because I would like your project to live long.

**Comment by KKonst27** [comment]
A good idea to develop to reduce the impact of multi-accounts.
I also think that it is necessary to introduce some kind of mechanics that would require some attention from the players on an ongoing basis. For example, you can make it so that after the attack of goblins, some beds and buildings would become unusable and they would have to be restored for the resources that we extract. Well, or in extreme cases, such resources could be bought from other players.
Such mechanics will allow you to accumulate more tokens, resources. In addition, it will give greater importance to the economy, the interaction of players with each other.
It is important that for more developed farms this burning is more efficient, so that the players **WILL MEAN TO UPGRADE THEIR FARM TO THE MAXIMUM,**

**Comment by SuperSynapse** [comment]
I like the idea, but the reality is those with many farms can always do what a single farm would do in each farm. Any leftover SFL or resources allow them the be the first to grab all the NFTs and first to profit. 

**Even having 2 farms gives someone a HUGE advantage relative to someone with one.**

The decision to make the game a "one account only and we'll police it", although noble, is a massive undertaking. I personally don't even think it's possible, unless you make the game incredibly invasive in harvesting data, KYC, and accept some people will get banned by accident.

Real players are getting left behind and I don't think the devs or the community have the stomach to ban 75% of all farms that exist right now. The collateral damage will be massive.

I've seen people IN THE SFL DISCORD streaming 50+ farms and the entire chat talking about how easy it is. VPN, discord verification service for $0.25, only open one account as a time. That's all they are doing. All day long.

At the end of the day I feel this is the single biggest issue, because people with one farm are left with no option but to buy many of the NFTs on opensea from the people who are multifarming for massive gains and it will only get worse, and push legitimate players to lose trust in the game's future.

**Comment by SuperSynapse** [comment]
To end with a positive comment, I LOVE what is being created here, and this is literally the coolest play to earn I've ever seen.
- Anyone can play for 1 Matic
- Community driven and people like myself can express/participate with their art.
- Fun, colorful environment
- Lots of updates and things to work towards
- An incredible team who cares and is involved.

I so badly want to see this project succeed, so take any of my prior comment as constructive criticism from someone who has a lot of experience in crypto and knows where to look to find people getting around arbitrary rules.

**Comment by RickFaker** [comment]
about multi-accounts. I would like to propose the following: there are 2 people, one of them has one very developed account (which has many open beds, for example 220). the second has 10 accounts, which are not developed and he also has 220 beds. I think that there should be a system that would force the dishonest player to spend a lot of time. For example: a system of watering or taking care of the earth. honest player needs to water the plants on their first 22 beds, and the rest of the open beds (220 pieces), flow automatically. dishonest player will need to water each account separately, which will take 10 times more time. this should take about 30 minutes a day for an honest player and 30*10
 someone who has a lot of accounts, at this point spends very little time maintaining them.

**Comment by RickFaker** [comment]
I'm sorry, but I'm going to be a little direct in my statements. i've never been involved in game development and i probably don't own the situation and have a very misguided opinion. i'm a fan of this game and i save up a lot of resources without selling them.
At the moment the economy of the game, keeps on those who believe in the project. game fans buy on the market from those who have many accounts and sell all the resources. at the moment fans have losses, because all nft have fallen in price, and to craft them first it is not possible because of the large number of resources from dishonest players. honest players have a loss, and not honest have good profit. faith in the project resource people tend to end. what happens when people stop believing in the project - they also start to sell all their assets. ... what will happen to the price of the assets and will synchronization cost more than what they have earned in the game? i think the issue of multi-accounts is more important than any other issues. all these bees, fishing and everything else can wait, the priorities must be set correctly. this is like the situation when a person has built a good, three-story house, but the first floor of the house starts to burn. at this time, the man is engaged in other, important things, like laying pipes and electricity to the house. he has no time to put out the fire ... This is an economic game and without proper economics it will not be of interest to anyone, because there are many farm simulators among the regular games.
I watched ama and translated the text from the video, even though there were no subtitles (I left a comment about it on YouTube).
I saw the developers and they give the impression of open and good people. honest players are also good players, and those who use many accounts are not good people)))). will the bad people beat the good ones this time too? ))))
I apologize to the team and fans of the game if I allowed myself to be redundant in my remarks.
