### ISSUE TITLE
[QUESTION] Art Guidelines Improvement

### ISSUE THREAD

**Issue by birborbirb** [sunflower-land/sunflower-land#863]
It's a common sense the current art guidelines need some improviments and would be really helpful if you comment here your ideas and doubts about any topic we should add or improve to the art guidelines. I'll be working to improve it on the next few days!
Please check this link and give your opinion: 

https://github.com/sunflower-land/sunflower-land/blob/main/docs/ART_CONTRIBUTING.md

Here's a list of issues I'm already aware of: 

- Colour palette
- Dimension Guidelines
- How to test & submit art
- Animation Guidelines
- Plagiarism Guidelines

**Comment by Alexcnder** [comment]
First thing i would add to the Site is to add the Color Pallete

**Comment by LeShykun** [comment]
I think we should add something that keep people engaged with submitting arts! Maybe can add something like ( if you contribute a lot to the project you can get a certified art contributor role + an artist badge ) think this should be added so people feel they get something back from the game **opinion**

**Comment by LittleEins** [comment]
> First thing i would add to the Site is to add the Color Pallete

Same thoughts.

**Comment by DonatasDee** [comment]
I don't know how to word this but I think its important for the team and artists themselves to take in to mind when creating art to not try to make this a marvel movie or a sculpture park - we need to incentivize creativity while still keeping a consistent theme going.

**Comment by SuperSynapse** [comment]
Thanks Birb! If you have any questions from our conversation let me know. I'll be following this post for any updates! :D

**Comment by Netherzapdos** [comment]
Perhaps also showcase some work from the community that's gotten into the game. It would serve as a reference for future artists in learning how to design and color in SFL style. 

I would suggest organizing them by categories: Landscape Art/Water-related Art/Animal Art/UI Designs/etc.

**Comment by gd-cloud** [comment]
I think it’s almost all about consistency. As a game developer I’ve have leaned how to share most part of my ideas being respectful to what this word means. This is a very subtle subject but I will try to be as clear as I can on how I do see consistency when applied to game art. This is not just about bringing real or fantasy worlds things and adapting them to the game aesthetics using the game color palette. Everything in the game needs to make sense in the most various cognitive ways, from the way how an npc talks to the sound the users hear when they click on an interface button. To have a consistent theme going,  we need first to have a solid theme. I think Farmers and goblins are not enough to keep things consistent. Due to the lack of the games background story, this can be quite challenging for the artists, that also would need to adventure themselves in the world of game writing. Since there isn’t an art director or lead artist in the team, artists can feel kind of lost on their own creativity crossroads. I would suggest clearly art requests coming from the game writing team.      Stimulating creativity through competitions could not be the best way to maximize the community artists productivity, since most of them will be only wasting their time other than working on something actually useful for the game.

**Comment by sfwhat** [comment]
Maybe you could include some suggestions about where to draw pixelart like aseprite,piskel or pixilart. It is a frequently asked question in artists chat.

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
