### ISSUE TITLE
[IDEA] ⚠️SFL rate for the next 50k farms

### ISSUE THREAD

**Issue by SrCouve** [sunflower-land/sunflower-land#881]
I think my proposal will go nowhere, but I would still like to share a little of my vision (which is not absolute truth, just my point of view)

**In my opinion, it is extremely necessary  an SFL rate (I suggest something between 10 and 50) to mint the next 50k of farms that start soon**

People who really wanted to get into the game, have already bought farms in the open sea for 20 dollars, with the wheat upgrade released, as I've seen several out there, those who haven't entered yet and are waiting for the farm to be released for 1 maitc will probably make minimal investment and not buy any SFL, and in a few days will be withdrawing this being a bad point for the economy, a fee in SFL to mint the next farms in my view is something healthy and necessary at the current moment, these SFLs can be burned, go for liquidity or for the well

another option:
I think it would be interesting to have a system where you need an NFT to withdraw, put the value of this NFT in SFL, unlimited stock, something around 10/20sf lthat way anyone can enter the game for a low price and farm to buy their NFT, or buy the SFL to buy it directly, the entry barrier would be intact, to withdraw you would need to have it, it would be more of a barrier than the mults, and bots, or a system where the amount you can withdraw in SFL is linked to the amount of SFL you burned

**Comment by DonatasDee** [comment]
I get the idea but in reality get like 2 SFL per day as a new farm, then also get taxed 30% percent.

Adam mentioned maybe in the future having people lock an amount of Matic that gets returned if the player is fair.

**Comment by ElcomJ31** [comment]
My point of view on the SFL rate to get into the game is pretty straight to the point.

The proposal is necessary, it's no use trying to fool around saying that they're going to return matic, that the game is for everyone because this idea of ​​a happy community doesn't work in blockchain games, and an entry fee in SFL is necessary to be able to mint new farms, since they had the idea that the whole farm could be sold as an NFT and not just the craftable items.

Tell me, if you're a new player what would you prefer?
Go straight to open sea and buy a lvl 4 farm with everything released, or pay 1 - 10 matic and gradually level up?

It's your choice, if you want to see the game die little by little, thinking that the price of the SFL will go up to 1 or 6 Dol one day as it is, keep dreaming while the others are trading and profiting.

If you really want to make a game that lasts like Axie Infinity and others, think about the choices you're going to make now.

Thank you and have a great day.

**Comment by ElcomJ** [comment]
My point of view on the SFL rate to get into the game is pretty straight to the point.

The proposal is necessary, it's no use trying to fool around saying that they're going to return matic, that the game is for everyone because this idea of ​​a happy community doesn't work in blockchain games, and an entry fee in SFL is necessary to be able to mint new farms, since they had the idea that the whole farm could be sold as an NFT and not just the craftable items.

Tell me, if you're a new player what would you prefer?
Go straight to open sea and buy a lvl 4 farm with everything released, or pay 1 - 10 matic and gradually level up?

It's your choice, if you want to see the game die little by little, thinking that the price of the SFL will go up to 1 or 6 Dol one day as it is, keep dreaming while the others are trading and profiting.

If you really want to make a game that lasts like Axie Infinity and others, think about the choices you're going to make now.

Thank you and have a great day.

**Comment by EB177** [comment]
i kind of agree with having an sfl rate .  like @ElcomJ said would you rather buy a maxed out farm for 20 bucks or start fresh for 1-10 matic. Feel like it could also be a good burning mechanic for sfl having the new player pay 10 matic (that will get returned and 25-50 sfl is a good idea anyway thats just my opinion

**Comment by vrillx** [comment]
No ... cheap sfl is good for the game ... we dont need to burn sfl right now ..the halvening already doing its thing and its already very hard to aquire more..what you suggest would just put pressure on sfl and personally i dont want to see that ..i want to see sfl getting cheaper and players able to produce more of it daily once animals land ... 
Cheap sfl = cheap mining = cheap nft = accessible to everyone
Expensive sfl = expensive mining = expensive nft = accesible to 1% only
