### ISSUE TITLE
(Question) Will you block the ''trillion'' resources banked in opensea from destroying the economy ?

### ISSUE THREAD

**Issue by vrillx** [sunflower-land/sunflower-land#908]
1 .Its pretty obvious by now that resource supplies shown in opensea are not what V2 players produced ... A large procentage of opensea resources come from V1 players who produced them using multiaccounts which pretty much makes them illegal resources , not to mention the exploit which (if im not wrong)  made material cost of in-game materials cheaper in V1.

2.Pretty sure everyone knows by now multiaccounting is still a big issue in the game and its easily observable on opensea by watching parent accounts transfering resources to them daily from dozens of other accounts...day in, day out ..thats all they do . Why ? Because multiaccounters know that as long as they keep transfering resources to opensea everyday then they dont care if they get banned ....theyre resources and nft will be safe on opensea and they will be able to sell them and make profits. 

 3.I was checking total supply today on opensea for chickens and eggs and to my surprise the total was 7500 chickens and 64000 eggs..i mean seriously they are not even available ingame and yet people already have huge amounts...By the end of the month you are probably gonna announce unlocking the chicken coop nft ..and they will probably be gone in few days ...and honest players like myself who btw invested thousands of dollars in v2 will probbaly get none because there wont be time enough to actually get any eggs.

 4.Seems version 1 players and beta testers are getting all the good stuff so far with T3 golden cauliflower, kuebiko, beaver almost all going to people with huge stockpiles already ..What im trying to say is you are not making this game very fair for V2 players . Soon market on rarible will be available and i have a feeling people will be so desperate to get rid of those millions of resource supply they will sell them for nothing ...and we the v2 players who have to pay 8 sfl to dig 1 gold ore will watch helplesly how our investments are devalued .

I dont know how/ or if you intend to actually do something about the insane amount of resources on opensea but if you dont the value in the game will start to dissapear very quickly .

So my question for the developers stands 

Will you block the trilion resources banked in opensea from getting ingame and destroying the economy ?

**Comment by Stevew00dy** [comment]
Are you able to back up your theories with any evidence please to support them.

To answer your points meanwhile:

1, Multi accounting in version 1 was not illegal. Any assets moved over were from real players. We know this because any bots in version 1 were not able to port their assets and so they were not converted into version 2. 

2, Moving assets from multiple accounts into one does not determine multi accounting. In some instances, people are working together, pooling resources. This is teamwork and not against the rules, however those who are caught multi accounting are banned and their resources are not able to be withdrawn. In the future you will have an in game marketplace, Opensea is a temp solution whilst that is being created. We have always told people to be aware when trading on 3rd party websites. We are not worried about the supply, looking at the on chain data, it's really not as bad as you suggest.

https://dune.com/zkblue/Sunflower-Land-Analytics

3, Those who were farming in version 1 got access to resources before those in version 2, that is not unfair, it's how it should be. There will be more than enough NFTs and future features and benefits to support all players no matter what time they join. 

Looking forward to you presenting the numbers to backup the trillions of assets you mentioned.

**Comment by Stevew00dy** [comment]
Are you able to back up your theories with any evidence please to support them.

To answer your points meanwhile:

1, Multi accounting in version 1 was not illegal. Any assets moved over were from real players. We know this because any bots in version 1 were not able to port their assets and so they were not converted into version 2. 

2, Moving assets from multiple accounts into one does not determine multi accounting. In some instances, people are working together, pooling resources. This is teamwork and not against the rules, however those who are caught multi accounting are banned and their resources are not able to be withdrawn. In the future you will have an in game marketplace, Opensea is a temp solution whilst that is being created. We have always told people to be aware when trading on 3rd party websites. We are not worried about the supply, looking at the on chain data, it's really not as bad as you suggest.

https://dune.com/zkblue/Sunflower-Land-Analytics

3, Those who were farming in version 1 got access to resources before those in version 2, that is not unfair, it's how it should be. There will be more than enough NFTs and future features and benefits to support all players no matter what time they join. 

Looking forward to you presenting the numbers to backup the trillions of assets you mentioned.

**Comment by Stevew00dy** [comment]
Are you able to back up your theories with any evidence please to support them.

To answer your points meanwhile:

1, Multi accounting in version 1 was not illegal. Any assets moved over were from real players. We know this because any bots in version 1 were not able to port their assets and so they were not converted into version 2. 

2, Moving assets from multiple accounts into one does not determine multi accounting. In some instances, people are working together, pooling resources. This is teamwork and not against the rules, however those who are caught multi accounting are banned and their resources are not able to be withdrawn. In the future you will have an in game marketplace, Opensea is a temp solution whilst that is being created. We have always told people to be aware when trading on 3rd party websites. We are not worried about the supply, looking at the on chain data, it's really not as bad as you suggest.

https://dune.com/zkblue/Sunflower-Land-Analytics

3, Those who were farming in version 1 got access to resources before those in version 2, that is not unfair, it's how it should be. There will be more than enough NFTs and future features and benefits to support all players no matter what time they join. 

Looking forward to you presenting the numbers to backup the trillions of assets you mentioned.

**Comment by vrillx** [comment]
The ''trillion'' resources was a figure of speech ..obviously theyre not that many.

As a v2 player i feel ,the fact that you allowed all these resources from V1 ( where 1 person could operate dozens more accounts) to literally flood v2 market ... puts me at a great disadvantage ... 

Wish you would have given us a clean slate so we dont have to have this system where v1 players have to get theyre money back from version 2 players .... The nft marketplace on opensea is a race to the bottom , everything v1 players could grab from nft store has been grabbed and its up for sale for mere pennies of their value ... 

99% of of major resource holders on opensea are unnamed accounts with resources hidden. Some have banned farms on their accounts and transfers continue daily from other farms... thats exactly what normal players working together do.... anyway  i cant prove they are multiaccounting , just as you cant prove they are all working together fot he benefit of the group ...it is indeed alot of speculation for my part ...it is hopefully a problem that land expansion will solve ....
I guess when resource trading on rarible becomes available we get to see the impact these resources that have been brought over form v1 will have on the economy .... they already crashed the nft market lets see how the resource market will go... i hope im wrong ....


Question 1- is it true so far only v1 players/betatesters have liquidity provider badges ? If yes then thats the kinda of thing should be avoided in the future , if im wrong then i guess people are just spreading rumours on discord..hope im worng cause i dont like seeing divides like these being created between v1 and v2 players... 

The ''wealth'' transfer from version 1 its been done and im just wasting my breath debating weather it is fair or not ... i just wanted to be made fair to v1 players ... as in ...no wonder we cant get any carrot swords nft when these guys transfered over 2 mil carrots ..how we gonna compete with that ? Thats just one example ... and if you say that someone growing carrots on 50 farms in version 1 brings them over and gets a carrot sword in V2 vs a v2 player who barely managed to get few hundred carrots , is fair...well lets agree to disagree...

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
