### ISSUE TITLE
(Proposal) Mysterious Parsnip needs buff

### ISSUE THREAD

**Issue by Sunflowerfarmer88** [sunflower-land/sunflower-land#913]
I suggest to buff the mysterious parsnip's effect. As we can see the demand for this almost t3 nft is very low, a bunny with carrots would be even more profitable than planting parsnips with this nft.

Btw I'm having green thumb skill here

Let's say 100 carrots with bunny, will cost you 1.25 SFL for seeds. And you get to sell 120 carrots for 2.52 SFL, thus profit is 1.27 SFL for roughly 4.5 hours assuming 100 seeds to be planted in 22 plots.

Now for mysterious parsnip, 22 seeds will cost you 2.75 SFL, and then would be able to sell it for  3.75375 SFL thus a profit of 1.00375 SFL which is to be planted for 6 hours.

So i guess it makes the bunny more effective than the mysterious parsnip in creating profits yet mysterious parsnip cost a lot of resources and almost on par with t3 nfts.

I hope for your favorable response :) More power.

**Comment by Silla420** [comment]
I agree with you, profit per day 22beds is around 4-5$SFL but I need like 500-600$SFL to craft so ROI is 100-120days!  It is not worth it, I would rather go for bunny

**Comment by PigaPigaPiga** [comment]
Nobody is forcing anybody to mint the NFTs they don't want, or that they may not need.. So in my opinion it's just fine as it is already. Let me elaborate:

The Mysterious Parsnip buff in itself may not be extremely strong and repay/ROI it's costs on it's own, but as many farming NFTs will be 'buffing' other NFTs with increasingly more effects, stacking/combining the Mysterious Parsnip with a couple more NFTs could greatly increase it's worth/value and shorten the ROI

As the Parsnip Seeds make up 80% of the Parsnip crop selling prices, so a Kuebiko will more than 5-double the daily SFL production for a Mysterious Parsnip holder right now (from 3.3 SFL profits a day to over 20 SFL a day), and combined with another few effects from either skills and/or contribution badges this could already get near 30 SFL a day already now.. And combined with other NFTs the Mysterious Parsnip actually ends up scaling up quicker with future additional bonuses than the Easter Bunny. But at this point of the game right now, the Mysterious Parsnip is actually already the way to obtain the highest possible daily SFL earnings, just not by using it all on it's own.


I do agree the Easter Bunny is an amazing NFT as well, it's hugely undervalued right now. Those Bunnys are also just a cheap entry into boosting SFL via Carrot production, and it'll end up coming down the which NFTs/effects are released in the future, and how their bonuses play into the effects of everything else

I'd actually advice towards not changing the Mysterous Parsnip at this point, firstly due to the reasons of people already having analysed, minted and/or traded it, and changing the effect this late would "look wrong" in the eyes of many who might then quickly have to reconsider if they'd have wanted one .. and now it might be too late to craft/obtain. And Secondly just because I think it's better to "undertune" NFTs and their powerlevel, and then let the future stacking of NFTs increase all their values/ROI/effects .. Rather than start designing/implementing super super overpowered NFTs this early, and at that price point/supply, because the stronger the effects the harder it's going to be to balance all/any effects to be designed and implemented in the future.. With smaller effects, it has less of a massive impact on the economy if someone in the future ends up crafting/using hundreds of them simultaniously.. It reduces the chance for some combination of NFTs to eventually spin completely out of control, in regards of future power-levels and effect balancing  


As always, remember to always DYOR. Just because a NFT is limited or costs a lot, that doesn't mean it's going to be ideal or worth it for everybody..  And the Mysterious Parsnip isn't actually a T3 NFT, it's just a 'rare/limited' NFT, that changes the way(/future game for how) Parsnips can be used (T3 NFTs are only NFTs that have had 2 steps below them of crafting, like Kuebiko starts as a Nancy that's upgraded into a Goblin Scarecrow and then finally into it's T3 Kuebiko version)

**Comment by KKonst27** [comment]
Mysterious Parsnips don't needs buff :D
![image](https://user-images.githubusercontent.com/103465383/168454933-a5c59fdc-508f-4def-9630-2dde1ff501d4.png)
![image](https://user-images.githubusercontent.com/103465383/168454947-f9071f5f-3d0f-494c-a9a4-1c16d6f334a7.png)

**Comment by Sunflowerfarmer88** [comment]
@KKonst27 Can you do a comparison of having only the bunny and mysterious parsnip nft.


Lucky for those who have the kuebiko (which is a small amount of people) that it removed the expense for buying seeds. 

What I'm stating here is that there is no significant advantage of having only the mysterious parsnip alone even though it is more rare than the bunny. You also showed it in the first picture. Look at the difference of having a golden cauliflower. Yet the bunny nft is more beneficial than having a rare mysterious parsnip in terms of earning SFL.

**Comment by brian-man** [comment]
Easter Bunny vs. Mysterious Parsnip -- no other buffs

![image](https://user-images.githubusercontent.com/36871683/168462218-e5f81e00-12a0-46dc-bf93-34878ace1a36.png)

**Comment by Sunflowerfarmer88** [comment]
@brian-man can i get the profit table thank you mate

**Comment by PigaPigaPiga** [comment]
> What I'm stating here is that there is no significant advantage of having only the mysterious parsnip alone even though it is more rare than the bunny. You also showed it in the first picture. Look at the difference of having a golden cauliflower. Yet the bunny nft is more beneficial than having a rare mysterious parsnip in terms of earning SFL.

The Bunny is only more efficent at earning SFL than the Mysterious Parsnip on it's own. As I also mentioned in my long text in the last reply here (please do read that, altho it's long).. 

The Mysterious Parsnip is also 5-6x easier to use though, as you only need to plant it so and so many times. 

If you compare a standard unbuffed Carrot to a standard unbuffed Parsnip, there's also going to be a difference 😅 That doesn't mean the Parsnip is too underpowered in general either, it's just balanced towards the workload needed to use and keep it up efficiently 😊

**Comment by adamhannigan** [comment]
Thanks for the contribution and feedback! ❤️ 

 We are moving towards using an ideas portal to help capture and vote on community ideas. Github will only be used for bug/technical reports. We are only a small team and it is becoming difficult for us to respond individually to every case so we have began using community voting software.   

 If you could please upload your idea to the following community portal it would be greatly appreciated 🤗   

 https://sunflower-land.ideas.aha.io/

 You can vote on similar ideas and help bring ideas to our attention. Thanks again for being apart of this community!
